// board_top_priority_sequenced.v -- GENERATED by tools/board_tests_v1.py (ledger #1023); do not hand-edit.
`default_nettype none
`timescale 1ns / 1ps
module board_top_priority_sequenced #(parameter integer CPB = 234, parameter integer SETTLE = 131072, parameter integer TIMEOUT = 33554432) (
    input wire BOARD_CLK, output wire UART_TX, output wire LED0_N, output wire LED1_N, output wire LED2_N, output wire LED3_N);
wire clk = BOARD_CLK;
reg [7:0] por_cnt = 8'h00; wire rst = (por_cnt != 8'hFF); always @(posedge clk) if (rst) por_cnt <= por_cnt + 8'd1;
reg [3:0] cfg_sr = 4'hF; always @(posedge clk) if (!rst) cfg_sr <= {cfg_sr[2:0], 1'b0};
wire cfg_valid = !rst && cfg_sr[3] && !cfg_sr[2];
reg [5:0] wait_cnt = 6'd0; reg started = 1'b0;
always @(posedge clk) if (!rst && !cfg_sr[3] && !started) begin wait_cnt <= wait_cnt + 6'd1; if (wait_cnt == 6'd8) started <= 1'b1; end
reg [31:0] lfsr = 32'hACE1ACE1; always @(posedge clk) lfsr <= {lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]};
reg done = 1'b0;
reg [31:0] mem_E1 [0:6]; integer idx_E1 = 0; reg act_E1 = 1'b0; wire ack_E1;
initial begin mem_E1[0] = 32'h0000000B; mem_E1[1] = 32'h0000000C; mem_E1[2] = 32'h0000000D; mem_E1[3] = 32'h0000000E; mem_E1[4] = 32'h0000000F; mem_E1[5] = 32'h00000010; mem_E1[6] = 32'h0; end
wire [31:0] d_E1 = mem_E1[idx_E1];
reg [31:0] mem_E2 [0:6]; integer idx_E2 = 0; reg act_E2 = 1'b0; wire ack_E2;
initial begin mem_E2[0] = 32'h00000015; mem_E2[1] = 32'h00000016; mem_E2[2] = 32'h00000017; mem_E2[3] = 32'h00000018; mem_E2[4] = 32'h00000019; mem_E2[5] = 32'h0000001A; mem_E2[6] = 32'h0; end
wire [31:0] d_E2 = mem_E2[idx_E2];
reg [31:0] mem_E3 [0:6]; integer idx_E3 = 0; reg act_E3 = 1'b0; wire ack_E3;
initial begin mem_E3[0] = 32'h0000001F; mem_E3[1] = 32'h00000020; mem_E3[2] = 32'h00000021; mem_E3[3] = 32'h00000022; mem_E3[4] = 32'h00000023; mem_E3[5] = 32'h00000024; mem_E3[6] = 32'h0; end
wire [31:0] d_E3 = mem_E3[idx_E3];
always @(posedge clk) if (started && !done) begin
    if (act_E1 && ack_E1) begin idx_E1 <= idx_E1 + 1; act_E1 <= 1'b0; end
    else if (!act_E1 && idx_E1 < 6 && 1'b1) act_E1 <= 1'b1;
    if (act_E2 && ack_E2) begin idx_E2 <= idx_E2 + 1; act_E2 <= 1'b0; end
    else if (!act_E2 && idx_E2 < 6 && 1'b1) act_E2 <= 1'b1;
    if (act_E3 && ack_E3) begin idx_E3 <= idx_E3 + 1; act_E3 <= 1'b0; end
    else if (!act_E3 && idx_E3 < 6 && 1'b1) act_E3 <= 1'b1;
end
wire [31:0] od; wire ov; wire oa = 1'b1;
icm_priority_sequenced_flex dut (.clk(clk), .rst(rst), .cfg_valid(cfg_valid), .in_E1_data(d_E1), .in_E1_valid(act_E1), .in_E1_ack(ack_E1), .in_E2_data(d_E2), .in_E2_valid(act_E2), .in_E2_ack(ack_E2), .in_E3_data(d_E3), .in_E3_valid(act_E3), .in_E3_ack(ack_E3), .out_O_data(od), .out_O_valid(ov), .out_O_ack(oa));
reg [31:0] expm [0:13]; initial begin expm[0] = 32'h0000001F; expm[1] = 32'h00000015; expm[2] = 32'h00000016; expm[3] = 32'h0000000B; expm[4] = 32'h00000020; expm[5] = 32'h00000017; expm[6] = 32'h00000018; expm[7] = 32'h0000000C; expm[8] = 32'h00000021; expm[9] = 32'h00000019; expm[10] = 32'h0000001A; expm[11] = 32'h0000000D; expm[12] = 32'h00000022; expm[13] = 32'h0; end
reg [15:0] cnt = 16'd0, bad = 16'd0; reg [31:0] sig = 32'd0, cyc = 32'd0, last = 32'd0, quiet = 32'd0; reg timed_out = 1'b0;
reg [31:0] w0 = 32'd0;
reg [31:0] w1 = 32'd0;
reg [31:0] w2 = 32'd0;
reg [31:0] w3 = 32'd0;
reg [31:0] w4 = 32'd0;
reg [31:0] w5 = 32'd0;
reg [31:0] w6 = 32'd0;
reg [31:0] w7 = 32'd0;
wire [15:0] want = 16'd13;
wire cap = ov && oa && started && !done;
always @(posedge clk) begin
    if (started && !done) begin
        cyc <= cyc + 32'd1; quiet <= quiet + 32'd1;
        if (cap) begin
            cnt <= cnt + 16'd1; last <= cyc; quiet <= 32'd0; sig <= {sig[30:0], sig[31]} ^ od;
            if (cnt >= want || od != expm[cnt]) bad <= bad + 16'd1;
            if (cnt == 16'd0) w0 <= od;
            if (cnt == 16'd1) w1 <= od;
            if (cnt == 16'd2) w2 <= od;
            if (cnt == 16'd3) w3 <= od;
            if (cnt == 16'd4) w4 <= od;
            if (cnt == 16'd5) w5 <= od;
            if (cnt == 16'd6) w6 <= od;
            if (cnt == 16'd7) w7 <= od;
        end
        if (cnt >= want && quiet >= SETTLE) done <= 1'b1;
        if (cyc >= TIMEOUT) begin done <= 1'b1; timed_out <= (cnt < want); end
    end
end
wire pass = done && !timed_out && (cnt == want) && (bad == 16'd0);
function [7:0] hexch(input [3:0] v); hexch = (v < 4'd10) ? (8'h30 + v) : (8'h41 + v - 4'd10); endfunction
reg [9:0] mi = 10'd0;
reg [7:0] msg_byte_r; function [7:0] msg_byte(input [9:0] i); begin case (i)
        10'd0: msg_byte = 8'h55;
        10'd1: msg_byte = 8'h43;
        10'd2: msg_byte = 8'h54;
        10'd3: msg_byte = 8'h20;
        10'd4: msg_byte = 8'h70;
        10'd5: msg_byte = 8'h72;
        10'd6: msg_byte = 8'h69;
        10'd7: msg_byte = 8'h6F;
        10'd8: msg_byte = 8'h72;
        10'd9: msg_byte = 8'h69;
        10'd10: msg_byte = 8'h74;
        10'd11: msg_byte = 8'h79;
        10'd12: msg_byte = 8'h5F;
        10'd13: msg_byte = 8'h73;
        10'd14: msg_byte = 8'h65;
        10'd15: msg_byte = 8'h71;
        10'd16: msg_byte = 8'h75;
        10'd17: msg_byte = 8'h65;
        10'd18: msg_byte = 8'h6E;
        10'd19: msg_byte = 8'h63;
        10'd20: msg_byte = 8'h65;
        10'd21: msg_byte = 8'h64;
        10'd22: msg_byte = 8'h20;
        10'd23: msg_byte = 8'h72;
        10'd24: msg_byte = 8'h65;
        10'd25: msg_byte = 8'h73;
        10'd26: msg_byte = 8'h3D;
        10'd27: msg_byte = pass ? 8'h50 : 8'h46;
        10'd28: msg_byte = 8'h20;
        10'd29: msg_byte = 8'h6E;
        10'd30: msg_byte = 8'h3D;
        10'd31: msg_byte = hexch((cnt >> 12) & 4'hF);
        10'd32: msg_byte = hexch((cnt >> 8) & 4'hF);
        10'd33: msg_byte = hexch((cnt >> 4) & 4'hF);
        10'd34: msg_byte = hexch((cnt >> 0) & 4'hF);
        10'd35: msg_byte = 8'h20;
        10'd36: msg_byte = 8'h65;
        10'd37: msg_byte = 8'h3D;
        10'd38: msg_byte = hexch((want >> 12) & 4'hF);
        10'd39: msg_byte = hexch((want >> 8) & 4'hF);
        10'd40: msg_byte = hexch((want >> 4) & 4'hF);
        10'd41: msg_byte = hexch((want >> 0) & 4'hF);
        10'd42: msg_byte = 8'h20;
        10'd43: msg_byte = 8'h62;
        10'd44: msg_byte = 8'h61;
        10'd45: msg_byte = 8'h64;
        10'd46: msg_byte = 8'h3D;
        10'd47: msg_byte = hexch((bad >> 12) & 4'hF);
        10'd48: msg_byte = hexch((bad >> 8) & 4'hF);
        10'd49: msg_byte = hexch((bad >> 4) & 4'hF);
        10'd50: msg_byte = hexch((bad >> 0) & 4'hF);
        10'd51: msg_byte = 8'h20;
        10'd52: msg_byte = 8'h74;
        10'd53: msg_byte = 8'h6F;
        10'd54: msg_byte = 8'h3D;
        10'd55: msg_byte = hexch(({15'd0, timed_out} >> 0) & 4'hF);
        10'd56: msg_byte = 8'h20;
        10'd57: msg_byte = 8'h6C;
        10'd58: msg_byte = 8'h61;
        10'd59: msg_byte = 8'h73;
        10'd60: msg_byte = 8'h74;
        10'd61: msg_byte = 8'h3D;
        10'd62: msg_byte = hexch((last >> 28) & 4'hF);
        10'd63: msg_byte = hexch((last >> 24) & 4'hF);
        10'd64: msg_byte = hexch((last >> 20) & 4'hF);
        10'd65: msg_byte = hexch((last >> 16) & 4'hF);
        10'd66: msg_byte = hexch((last >> 12) & 4'hF);
        10'd67: msg_byte = hexch((last >> 8) & 4'hF);
        10'd68: msg_byte = hexch((last >> 4) & 4'hF);
        10'd69: msg_byte = hexch((last >> 0) & 4'hF);
        10'd70: msg_byte = 8'h20;
        10'd71: msg_byte = 8'h73;
        10'd72: msg_byte = 8'h69;
        10'd73: msg_byte = 8'h67;
        10'd74: msg_byte = 8'h3D;
        10'd75: msg_byte = hexch((sig >> 28) & 4'hF);
        10'd76: msg_byte = hexch((sig >> 24) & 4'hF);
        10'd77: msg_byte = hexch((sig >> 20) & 4'hF);
        10'd78: msg_byte = hexch((sig >> 16) & 4'hF);
        10'd79: msg_byte = hexch((sig >> 12) & 4'hF);
        10'd80: msg_byte = hexch((sig >> 8) & 4'hF);
        10'd81: msg_byte = hexch((sig >> 4) & 4'hF);
        10'd82: msg_byte = hexch((sig >> 0) & 4'hF);
        10'd83: msg_byte = 8'h20;
        10'd84: msg_byte = 8'h77;
        10'd85: msg_byte = 8'h3D;
        10'd86: msg_byte = hexch((w0 >> 28) & 4'hF);
        10'd87: msg_byte = hexch((w0 >> 24) & 4'hF);
        10'd88: msg_byte = hexch((w0 >> 20) & 4'hF);
        10'd89: msg_byte = hexch((w0 >> 16) & 4'hF);
        10'd90: msg_byte = hexch((w0 >> 12) & 4'hF);
        10'd91: msg_byte = hexch((w0 >> 8) & 4'hF);
        10'd92: msg_byte = hexch((w0 >> 4) & 4'hF);
        10'd93: msg_byte = hexch((w0 >> 0) & 4'hF);
        10'd94: msg_byte = 8'h2C;
        10'd95: msg_byte = hexch((w1 >> 28) & 4'hF);
        10'd96: msg_byte = hexch((w1 >> 24) & 4'hF);
        10'd97: msg_byte = hexch((w1 >> 20) & 4'hF);
        10'd98: msg_byte = hexch((w1 >> 16) & 4'hF);
        10'd99: msg_byte = hexch((w1 >> 12) & 4'hF);
        10'd100: msg_byte = hexch((w1 >> 8) & 4'hF);
        10'd101: msg_byte = hexch((w1 >> 4) & 4'hF);
        10'd102: msg_byte = hexch((w1 >> 0) & 4'hF);
        10'd103: msg_byte = 8'h2C;
        10'd104: msg_byte = hexch((w2 >> 28) & 4'hF);
        10'd105: msg_byte = hexch((w2 >> 24) & 4'hF);
        10'd106: msg_byte = hexch((w2 >> 20) & 4'hF);
        10'd107: msg_byte = hexch((w2 >> 16) & 4'hF);
        10'd108: msg_byte = hexch((w2 >> 12) & 4'hF);
        10'd109: msg_byte = hexch((w2 >> 8) & 4'hF);
        10'd110: msg_byte = hexch((w2 >> 4) & 4'hF);
        10'd111: msg_byte = hexch((w2 >> 0) & 4'hF);
        10'd112: msg_byte = 8'h2C;
        10'd113: msg_byte = hexch((w3 >> 28) & 4'hF);
        10'd114: msg_byte = hexch((w3 >> 24) & 4'hF);
        10'd115: msg_byte = hexch((w3 >> 20) & 4'hF);
        10'd116: msg_byte = hexch((w3 >> 16) & 4'hF);
        10'd117: msg_byte = hexch((w3 >> 12) & 4'hF);
        10'd118: msg_byte = hexch((w3 >> 8) & 4'hF);
        10'd119: msg_byte = hexch((w3 >> 4) & 4'hF);
        10'd120: msg_byte = hexch((w3 >> 0) & 4'hF);
        10'd121: msg_byte = 8'h2C;
        10'd122: msg_byte = hexch((w4 >> 28) & 4'hF);
        10'd123: msg_byte = hexch((w4 >> 24) & 4'hF);
        10'd124: msg_byte = hexch((w4 >> 20) & 4'hF);
        10'd125: msg_byte = hexch((w4 >> 16) & 4'hF);
        10'd126: msg_byte = hexch((w4 >> 12) & 4'hF);
        10'd127: msg_byte = hexch((w4 >> 8) & 4'hF);
        10'd128: msg_byte = hexch((w4 >> 4) & 4'hF);
        10'd129: msg_byte = hexch((w4 >> 0) & 4'hF);
        10'd130: msg_byte = 8'h2C;
        10'd131: msg_byte = hexch((w5 >> 28) & 4'hF);
        10'd132: msg_byte = hexch((w5 >> 24) & 4'hF);
        10'd133: msg_byte = hexch((w5 >> 20) & 4'hF);
        10'd134: msg_byte = hexch((w5 >> 16) & 4'hF);
        10'd135: msg_byte = hexch((w5 >> 12) & 4'hF);
        10'd136: msg_byte = hexch((w5 >> 8) & 4'hF);
        10'd137: msg_byte = hexch((w5 >> 4) & 4'hF);
        10'd138: msg_byte = hexch((w5 >> 0) & 4'hF);
        10'd139: msg_byte = 8'h2C;
        10'd140: msg_byte = hexch((w6 >> 28) & 4'hF);
        10'd141: msg_byte = hexch((w6 >> 24) & 4'hF);
        10'd142: msg_byte = hexch((w6 >> 20) & 4'hF);
        10'd143: msg_byte = hexch((w6 >> 16) & 4'hF);
        10'd144: msg_byte = hexch((w6 >> 12) & 4'hF);
        10'd145: msg_byte = hexch((w6 >> 8) & 4'hF);
        10'd146: msg_byte = hexch((w6 >> 4) & 4'hF);
        10'd147: msg_byte = hexch((w6 >> 0) & 4'hF);
        10'd148: msg_byte = 8'h2C;
        10'd149: msg_byte = hexch((w7 >> 28) & 4'hF);
        10'd150: msg_byte = hexch((w7 >> 24) & 4'hF);
        10'd151: msg_byte = hexch((w7 >> 20) & 4'hF);
        10'd152: msg_byte = hexch((w7 >> 16) & 4'hF);
        10'd153: msg_byte = hexch((w7 >> 12) & 4'hF);
        10'd154: msg_byte = hexch((w7 >> 8) & 4'hF);
        10'd155: msg_byte = hexch((w7 >> 4) & 4'hF);
        10'd156: msg_byte = hexch((w7 >> 0) & 4'hF);
        10'd157: msg_byte = 8'h0D;
        10'd158: msg_byte = 8'h0A;
        default: msg_byte = 8'h20; endcase end endfunction
localparam integer MSGLEN = 159;
wire tx_busy; reg tx_start = 1'b0; reg [7:0] tx_data = 8'h00; reg [31:0] gapc = 32'd0; reg [1:0] ps = 2'd0;
board_uart_tx #(.CPB(CPB)) utx (.clk(clk), .start(tx_start), .data(tx_data), .tx(UART_TX), .busy(tx_busy));
always @(posedge clk) begin
    tx_start <= 1'b0;
    case (ps)
        2'd0: if (done) begin mi <= 10'd0; ps <= 2'd1; end
        2'd1: if (!tx_busy && !tx_start) begin tx_data <= msg_byte(mi); tx_start <= 1'b1; ps <= 2'd2; end
        2'd2: if (tx_busy) begin if (mi == MSGLEN - 1) begin gapc <= 32'd0; ps <= 2'd3; end else begin mi <= mi + 10'd1; ps <= 2'd1; end end
        2'd3: if (!tx_busy) begin gapc <= gapc + 32'd1; if (gapc >= SETTLE * 4) ps <= 2'd0; end
    endcase
end
reg [23:0] hb = 24'd0; always @(posedge clk) hb <= hb + 24'd1;
assign LED0_N = ~hb[23]; assign LED1_N = ~pass; assign LED2_N = ~(done && !pass); assign LED3_N = ~done;
endmodule
