#!/usr/bin/env python3
"""
gen_mesh_top.py -- points.md #889: generate a REAL, board-pin-bound top-level Verilog module wrapping
N instances (N=1 standalone, or a real 3x3 mesh) of ONE standalone cell shell, for real synthesis AND
real place-and-route timing on the Tang Nano 20K (nextpnr-himbaechel-gowin against the actual GW2A-18C
chip database).

WHY A WRAPPER IS NEEDED AT ALL: a raw shell's own ports (four 32-bit cardinal data buses in and out,
64-127 bit cfg_data, per-direction program/ack channels...) run to 140-500+ raw signal bits. The Tang
Nano 20K's QN88 package has only 66 I/O pins total. A standalone shell CANNOT be place-and-routed with
every port bound to a real package pin -- there simply aren't enough pins, even for the single cheapest
cell. So every top-level port here is one of: (a) tied to a real, GENUINELY UNCONSTRAINED top-level
stimulus (so nextpnr/yosys cannot constant-fold it away and give an artificially small/fast result --
the same anti-pruning discipline `project_assemble_v1.generate_top` already uses, `#554`), (b) wired to
a NEIGHBOR cell's own port in the mesh (real interconnect, not a package pin at all), or (c) tied to a
fixed, documented default (an "extra" feature port this test does not exercise, e.g. nano's hold_in).
Only 5 real pins are used, all already verified against the chip database in `docs/man/tang-nano-20k.man.json`
(`#887`): BOARD_CLK (pin 4), BTN_RST_N (pin 88), BTN_ENTRY (pin 87), LED0_N (pin 15), LED1_N (pin 16).

This measures the STANDALONE and 3x3-MESH cost of one cell type in a real, closed, pin-bound system --
it is NOT a claim about what the real UniCell architecture's actual interconnect (which runs between
cells across the die, not through package pins) would cost; see the generated file's own header comment.

Usage: python3 gen_mesh_top.py <cell_type> <n> [rows] [cols]   n=1 or n=9 (rows=cols=3)
Types: latch ram adder branch accumulator compare sequencer mul priority nano command
"""
import sys

# --- the "standard" shape: clk, rst, active_in_n/s/e/w, cfg_valid, cfg_data[W], data_in/arrived (32b x4),
# data_out/fire, ready_out, ready_in_n/s/e/w, ack_out/ack_in, program_in/done, prog_data_in/prog_arrived_in/
# prog_ack_out (32b/1b x4), freeze_in (single bit), plus per-type STATUS outputs (name, width).
STANDARD = {
    "latch":       dict(module="latch_shell_v1c",       core="latch_cell_v4c",       cfg_w=64,  status=[("status_latched", 1)]),
    "ram":         dict(module="ram_shell_v1c",         core="ram_cell_v4c",         cfg_w=80,  status=[("status_data_valid", 1)]),
    "adder":       dict(module="adder_shell_v1c",       core="adder_cell_v4c",       cfg_w=64,  status=[("status_data_valid", 1), ("status_a_arrived", 1)]),
    "branch":      dict(module="branch_shell_v1c",      core="branch_cell_v4c",      cfg_w=80,  status=[("status_data_valid", 1)]),
    "accumulator": dict(module="accumulator_shell_v1c", core="accumulator_cell_v4c", cfg_w=64,  status=[("status_negative", 1)]),
    "compare":     dict(module="compare_shell_v1c",     core="compare_cell_v4c",     cfg_w=64,  status=[("status_data_valid", 1)]),
    "sequencer":   dict(module="sequencer_shell_v1c",   core="sequencer_cell_v4c",   cfg_w=64,  status=[("status_seq_index", 2)]),
    "mul":         dict(module="mul_shell_v1c",         core="mul_cell_v4c",         cfg_w=64,  status=[("status_data_valid", 1), ("status_a_arrived", 1)]),
    "priority":    dict(module="priority_shell_v1c",    core="priority_cell_v4c",    cfg_w=64,  status=[("status_data_valid", 1), ("status_winning_dir", 2)]),
}
DIRS = [("n", "s"), ("s", "n"), ("e", "w"), ("w", "e")]   # (direction, opposite)


def cfg_expr_for(w):
    """A Verilog concatenation of width w built from the running 32-bit `lfsr`, not a replication of one
    raw bit -- avoids the collapse found in points.md #889's first version of this harness."""
    reps, rem = divmod(w, 32)
    parts = (["lfsr"] * reps) + ([f"lfsr[{rem - 1}:0]"] if rem else [])
    return "{" + ", ".join(parts) + "}"



HEADER = """// GENERATED by tools/gowin_sizing/gen_mesh_top.py (points.md #889) -- do not hand-edit.
// A REAL, board-pin-bound closed system wrapping {n} instance(s) of `{module}` ({rows}x{cols} mesh if >1),
// for real yosys synth_gowin + real nextpnr-himbaechel-gowin place-and-route against the actual
// GW2AR-LV18QN88C8/I7 part. Only 5 top-level ports exist, all verified board pins (docs/man/tang-nano-20k.*).
// This is a MEASUREMENT HARNESS, not a real UniCell system: the mesh interconnect here is real RTL wiring
// between real cell instances (that part IS the real architecture), but the 5 pins exist only so nextpnr has
// a closed, bindable design to place and route -- a real UniCell build's interconnect runs cell-to-cell on
// the die, not through package pins.
`default_nettype none
`timescale 1ns / 1ps

module {top} (
    input  wire BOARD_CLK,     // pin 4 -- real crystal input, used directly as the design's clk net
    input  wire BTN_RST_N,     // pin 88 -- active-low reset button
    input  wire BTN_ENTRY,     // pin 87 -- genuinely unconstrained stimulus (prevents constant-folding, #554's own fix)
    output wire LED0_N,        // pin 15 -- heartbeat (proves the design is genuinely clocking)
    output wire LED1_N         // pin 16 -- XOR-reduced "array_alive": real, non-prunable, depends on every cell
);

wire clk = BOARD_CLK;
reg [3:0] rst_sr = 4'hF;
always @(posedge clk) rst_sr <= {{rst_sr[2:0], ~BTN_RST_N}};
wire rst = rst_sr[3] | ~BTN_RST_N;

// Real 32-bit Galois LFSR, advancing every cycle, seed mixed with BTN_ENTRY (a genuine board input, not a
// hardcoded constant) -- points.md #889's own fix for a real collapse found in the first version of this
// harness: reusing ONE raw external bit for several live inputs in the same cycle let the synthesiser prove
// them algebraically identical and fold the whole cell under test away as dead logic (confirmed: the DUT's
// own cell instances contributed zero surviving DFFs). Different LFSR bits/words look like independent,
// non-provably-related signals to the synthesiser, the same anti-collapse principle real BIST pseudo-random
// pattern generators rely on, since each is a genuine register with feedback, not a compile-time constant.
reg [31:0] lfsr = 32'hACE1_1234;
wire lfsr_fb = lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0] ^ BTN_ENTRY;
always @(posedge clk) if (!rst) lfsr <= {{lfsr[30:0], lfsr_fb}};

// Real, one-shot, broadcast config-load pulse (matches project_assemble_v1.generate_top's own proven
// anti-collapse fix, points.md #554): cfg_valid fires exactly once after reset; cfg_data is derived from
// the running LFSR (never a fixed value the synthesiser could prove constant).
reg [3:0] cfg_pulse_sr = 4'hF;
always @(posedge clk) if (!rst) cfg_pulse_sr <= {{cfg_pulse_sr[2:0], 1'b0}};
wire cfg_valid_bcast = !rst && cfg_pulse_sr[3] && !cfg_pulse_sr[2];
wire [{cfg_w_hi}:0] cfg_data_bcast = {cfg_expr};
wire [31:0] entry_data = lfsr;
wire [31:0] entry_data_s = {{lfsr[15:0], lfsr[31:16]}};    // distinct per-direction LFSR-derived data (not a raw
wire [31:0] entry_data_e = ~lfsr;                         // repeated bit and not a hardcoded zero) -- points.md
wire [31:0] entry_data_w = {{lfsr[7:0], lfsr[31:8]}};    // #889: a cell whose real core routes data via a
wire entry_active = lfsr[3];      // config-selected upstream/downstream mask can pick ANY of the 4 directions;
wire entry_arrived = lfsr[7];     // if 3 of 4 are hardcoded 0 and the mask happens to select one of THOSE, the
wire entry_active_s = lfsr[11];   // whole compute core sees a constant zero and gets optimized away entirely
wire entry_arrived_s = lfsr[13];  // (confirmed: this happened to `mul`, whose post-place cells were byte-for-
wire entry_active_e = lfsr[17];   // byte identical to `adder`'s). So EVERY direction of a standalone (no
wire entry_arrived_e = lfsr[19];  // neighbor) cell carries genuinely live, mutually-distinct data -- not just
wire entry_active_w = lfsr[23];   // the one this generator originally called "the entry point".
wire entry_arrived_w = lfsr[29];
wire [31:0] entry_data_n = entry_data;      // aliases: any row/col-0 cell missing a north/west neighbor
wire entry_active_n = entry_active;         // (not just cell (0,0) itself) hits this same fallback name
wire entry_arrived_n = entry_arrived;

reg [23:0] hb_cnt = 0;
always @(posedge clk) hb_cnt <= hb_cnt + 24'd1;
assign LED0_N = ~hb_cnt[23];

"""

FOOTER = """
wire array_alive = {xor_expr};
assign LED1_N = ~array_alive;
endmodule
"""


def inst_name(r, c):
    return f"c_{r}_{c}"


def gen_standard(cell_type, n, rows, cols):
    cfg = STANDARD[cell_type]
    module, cfg_w = cfg["module"], cfg["cfg_w"]
    positions = [(r, c) for r in range(rows) for c in range(cols)][:n]
    pos_set = set(positions)
    top = f"mesh_{cell_type}_{n}"

    lines = [HEADER.format(top=top, n=n, module=module, rows=rows, cols=cols, cfg_w_hi=cfg_w - 1, cfg_expr=cfg_expr_for(cfg_w))]
    for (r, c) in positions:
        nm = inst_name(r, c)
        lines.append(f"wire [31:0] {nm}_dout_n, {nm}_dout_s, {nm}_dout_e, {nm}_dout_w;")
        lines.append(f"wire {nm}_fire_n, {nm}_fire_s, {nm}_fire_e, {nm}_fire_w;")
        lines.append(f"wire {nm}_ack_n, {nm}_ack_s, {nm}_ack_e, {nm}_ack_w;")
    lines.append("")

    xor_terms = []
    for idx, (r, c) in enumerate(positions):
        nm = inst_name(r, c)

        def neighbor(nr, nc):
            return inst_name(nr, nc) if (nr, nc) in pos_set else None

        nbrs = {"n": neighbor(r - 1, c), "s": neighbor(r + 1, c), "e": neighbor(r, c + 1), "w": neighbor(r, c - 1)}

        def data_in(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_dout_{opp}"
            return "entry_data" if (d == "n" and idx == 0) else f"entry_data_{d}"

        def active_of(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_fire_{opp}"
            return "entry_active" if (d == "n" and idx == 0) else f"entry_active_{d}"

        def arrived_of(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_fire_{opp}"
            return "entry_arrived" if (d == "n" and idx == 0) else f"entry_arrived_{d}"

        def ack_in(d, opp):
            nb = nbrs[d]
            return "1'b0" if nb is None else f"{nb}_ack_{opp}"

        lines.append(f"{module} #(.CELL_ID(16'h{0x1000 + idx:04X})) {nm} (")
        lines.append("    .clk(clk), .rst(rst),")
        for d, opp in DIRS:
            lines.append(f"    .active_in_{d}({active_of(d, opp)}),")
        lines.append("    .cfg_valid(cfg_valid_bcast), .cfg_data(cfg_data_bcast),")
        for d, opp in DIRS:
            lines.append(f"    .data_in_{d}({data_in(d, opp)}), .arrived_{d}({arrived_of(d, opp)}),")
        lines.append(f"    .data_out_n({nm}_dout_n), .data_out_s({nm}_dout_s), .data_out_e({nm}_dout_e), .data_out_w({nm}_dout_w),")
        lines.append(f"    .fire_n({nm}_fire_n), .fire_s({nm}_fire_s), .fire_e({nm}_fire_e), .fire_w({nm}_fire_w),")
        lines.append("    .ready_out(), .ready_in_n(1'b1), .ready_in_s(1'b1), .ready_in_e(1'b1), .ready_in_w(1'b1),")
        lines.append(f"    .ack_out_n({nm}_ack_n), .ack_out_s({nm}_ack_s), .ack_out_e({nm}_ack_e), .ack_out_w({nm}_ack_w),")
        for d, opp in DIRS:
            lines.append(f"    .ack_in_{d}({ack_in(d, opp)}),")
        for d, _ in DIRS:
            lines.append(f"    .freeze_in_{d}(1'b0),")
        lines.append("    .program_in(1'b0), .program_done(),")
        lines.append("    .prog_data_in_n(32'h0), .prog_data_in_s(32'h0), .prog_data_in_e(32'h0), .prog_data_in_w(32'h0),")
        lines.append("    .prog_arrived_in_n(1'b0), .prog_arrived_in_s(1'b0), .prog_arrived_in_e(1'b0), .prog_arrived_in_w(1'b0),")
        lines.append("    .prog_ack_out_n(), .prog_ack_out_s(), .prog_ack_out_e(), .prog_ack_out_w(),")
        for name, width in cfg["status"]:
            lines.append(f"    .{name}(),")
            # (left unconnected is fine for LUT/FF sizing+timing: an unread output doesn't feed the XOR
            #  guard, so instead we tap fire_* and dout_*[0] below -- the same real anti-pruning signal
            #  set `generate_top` uses, proven not to let Quartus/yosys collapse the array.)
        lines[-1] = lines[-1].rstrip(",\n") + "\n);\n"
        # points.md #889: XOR-reduce the FULL 32-bit width of every dout, not one bit -- observing only
        # bit 0 let the synthesiser correctly (not a bug) prune 31/32 of the real arithmetic as unobserved,
        # which is why the first version of this fix made `adder` and `mul` synthesise byte-identical.
        xor_terms.extend([f"{nm}_fire_n", f"{nm}_fire_s", f"{nm}_fire_e", f"{nm}_fire_w",
                           f"^{nm}_dout_n", f"^{nm}_dout_s", f"^{nm}_dout_e", f"^{nm}_dout_w"])

    lines.append(FOOTER.format(xor_expr=" ^ ".join(xor_terms)))
    return "\n".join(lines)


def gen_nano(n, rows, cols):
    """nano_shell_v1c: a richer cardinal control surface than the standard shells (freeze_in_n/s/e/w plus
    hold_in/fb_internal_in/a_reemit_in/a_update_in/a_self_update_in, each n/s/e/w) and no `status_*`/
    `freeze_in` of its own; cfg_data is 128 bits. The extra control inputs are tied to 0 (not exercised by
    this baseline test) -- the same "tied off" default the carrier's own first RTL build already uses for
    these nano `extras` (`#880`/`#886`)."""
    positions = [(r, c) for r in range(rows) for c in range(cols)][:n]
    pos_set = set(positions)
    top = f"mesh_nano_{n}"
    lines = [HEADER.format(top=top, n=n, module="nano_shell_v1c", rows=rows, cols=cols, cfg_w_hi=127, cfg_expr=cfg_expr_for(128))]
    for (r, c) in positions:
        nm = inst_name(r, c)
        lines.append(f"wire [31:0] {nm}_dout_n, {nm}_dout_s, {nm}_dout_e, {nm}_dout_w;")
        lines.append(f"wire {nm}_fire_n, {nm}_fire_s, {nm}_fire_e, {nm}_fire_w;")
        lines.append(f"wire {nm}_ack_n, {nm}_ack_s, {nm}_ack_e, {nm}_ack_w;")
    lines.append("")
    xor_terms = []
    for idx, (r, c) in enumerate(positions):
        nm = inst_name(r, c)

        def neighbor(nr, nc):
            return inst_name(nr, nc) if (nr, nc) in pos_set else None
        nbrs = {"n": neighbor(r - 1, c), "s": neighbor(r + 1, c), "e": neighbor(r, c + 1), "w": neighbor(r, c - 1)}

        def data_in(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_dout_{opp}"
            return "entry_data" if (d == "n" and idx == 0) else f"entry_data_{d}"

        def active_of(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_fire_{opp}"
            return "entry_active" if (d == "n" and idx == 0) else f"entry_active_{d}"

        def arrived_of(d, opp):
            nb = nbrs[d]
            if nb is not None:
                return f"{nb}_fire_{opp}"
            return "entry_arrived" if (d == "n" and idx == 0) else f"entry_arrived_{d}"

        def ack_in(d, opp):
            nb = nbrs[d]
            return "1'b0" if nb is None else f"{nb}_ack_{opp}"

        lines.append(f"nano_shell_v1c #(.CELL_ID(16'h{0x1000 + idx:04X})) {nm} (")
        lines.append("    .clk(clk), .rst(rst),")
        for d, opp in DIRS:
            lines.append(f"    .active_in_{d}({active_of(d, opp)}),")
        for d, _ in DIRS:
            lines.append(f"    .freeze_in_{d}(1'b0), .hold_in_{d}(1'b0), .fb_internal_in_{d}(1'b0),")
            lines.append(f"    .a_reemit_in_{d}(1'b0), .a_update_in_{d}(1'b0), .a_self_update_in_{d}(1'b0),")
        lines.append("    .cfg_valid(cfg_valid_bcast), .cfg_data(cfg_data_bcast),")
        for d, opp in DIRS:
            lines.append(f"    .data_in_{d}({data_in(d, opp)}), .arrived_{d}({arrived_of(d, opp)}),")
        lines.append(f"    .data_out_n({nm}_dout_n), .data_out_s({nm}_dout_s), .data_out_e({nm}_dout_e), .data_out_w({nm}_dout_w),")
        lines.append(f"    .fire_n({nm}_fire_n), .fire_s({nm}_fire_s), .fire_e({nm}_fire_e), .fire_w({nm}_fire_w),")
        lines.append("    .ready_out(), .ready_in_n(1'b1), .ready_in_s(1'b1), .ready_in_e(1'b1), .ready_in_w(1'b1),")
        lines.append(f"    .ack_out_n({nm}_ack_n), .ack_out_s({nm}_ack_s), .ack_out_e({nm}_ack_e), .ack_out_w({nm}_ack_w),")
        for d, opp in DIRS:
            lines.append(f"    .ack_in_{d}({ack_in(d, opp)}),")
        lines.append("    .program_in(1'b0), .program_done(),")
        lines.append("    .prog_data_in_n(32'h0), .prog_data_in_s(32'h0), .prog_data_in_e(32'h0), .prog_data_in_w(32'h0),")
        lines.append("    .prog_arrived_in_n(1'b0), .prog_arrived_in_s(1'b0), .prog_arrived_in_e(1'b0), .prog_arrived_in_w(1'b0),")
        lines.append("    .prog_ack_out_n(), .prog_ack_out_s(), .prog_ack_out_e(), .prog_ack_out_w()")
        lines[-1] = lines[-1] + "\n);\n"
        # points.md #889: XOR-reduce the FULL 32-bit width of every dout, not one bit -- observing only
        # bit 0 let the synthesiser correctly (not a bug) prune 31/32 of the real arithmetic as unobserved,
        # which is why the first version of this fix made `adder` and `mul` synthesise byte-identical.
        xor_terms.extend([f"{nm}_fire_n", f"{nm}_fire_s", f"{nm}_fire_e", f"{nm}_fire_w",
                           f"^{nm}_dout_n", f"^{nm}_dout_s", f"^{nm}_dout_e", f"^{nm}_dout_w"])
    lines.append(FOOTER.format(xor_expr=" ^ ".join(xor_terms)))
    return "\n".join(lines)


def gen_command(n):
    """command_shell_v1c: a controller, not a data-mesh cell (freeze_out/program_out instead of the
    standard data_out/ack_out shape). Not tiled in a real data mesh, so this instantiates N independent
    copies with every neighbor-facing port tied off (no mesh wiring), which is the honest, self-consistent
    reading for this cell type."""
    top = f"mesh_command_{n}"
    lines = [HEADER.format(top=top, n=n, module="command_shell_v1c", rows=1, cols=n, cfg_w_hi=63, cfg_expr=cfg_expr_for(64))]
    xor_terms = []
    for idx in range(n):
        nm = f"c_{idx}"
        lines.append(f"wire {nm}_status_active, {nm}_status_freeze_state, {nm}_ready_out;")
        lines.append(f"command_shell_v1c #(.CELL_ID(16'h{0x1000 + idx:04X})) {nm} (")
        lines.append("    .clk(clk), .rst(rst),")
        active_n = "entry_active" if idx == 0 else "1'b0"
        data_n = "entry_data" if idx == 0 else "32'h0"
        arrived_n = "entry_arrived" if idx == 0 else "1'b0"
        lines.append(f"    .active_in_n({active_n}), .active_in_s(1'b0), .active_in_e(1'b0), .active_in_w(1'b0),")
        lines.append("    .freeze_in_n(1'b0), .freeze_in_s(1'b0), .freeze_in_e(1'b0), .freeze_in_w(1'b0),")
        lines.append("    .cfg_valid(cfg_valid_bcast), .cfg_data(cfg_data_bcast),")
        lines.append(f"    .data_in_n({data_n}), .data_in_s(32'h0), .data_in_e(32'h0), .data_in_w(32'h0),")
        lines.append(f"    .arrived_n({arrived_n}), .arrived_s(1'b0), .arrived_e(1'b0), .arrived_w(1'b0),")
        lines.append("    .ack_out_n(), .ack_out_s(), .ack_out_e(), .ack_out_w(),")
        lines.append(f"    .ready_out({nm}_ready_out),")
        lines.append("    .freeze_out_n(), .freeze_out_s(), .freeze_out_e(), .freeze_out_w(),")
        lines.append("    .program_out_n(), .program_out_s(), .program_out_e(), .program_out_w(),")
        lines.append("    .prog_data_out_n(), .prog_data_out_s(), .prog_data_out_e(), .prog_data_out_w(),")
        lines.append("    .prog_arrived_out_n(), .prog_arrived_out_s(), .prog_arrived_out_e(), .prog_arrived_out_w(),")
        lines.append("    .prog_ack_in_n(1'b0), .prog_ack_in_s(1'b0), .prog_ack_in_e(1'b0), .prog_ack_in_w(1'b0),")
        lines.append("    .program_in(1'b0), .program_done(),")
        lines.append("    .prog_data_in_n(32'h0), .prog_data_in_s(32'h0), .prog_data_in_e(32'h0), .prog_data_in_w(32'h0),")
        lines.append("    .prog_arrived_in_n(1'b0), .prog_arrived_in_s(1'b0), .prog_arrived_in_e(1'b0), .prog_arrived_in_w(1'b0),")
        lines.append("    .prog_ack_out_n(), .prog_ack_out_s(), .prog_ack_out_e(), .prog_ack_out_w(),")
        lines.append(f"    .status_active({nm}_status_active), .status_freeze_state({nm}_status_freeze_state)")
        lines[-1] = lines[-1] + "\n);\n"
        xor_terms.extend([f"{nm}_status_active", f"{nm}_status_freeze_state", f"{nm}_ready_out"])
    lines.append(FOOTER.format(xor_expr=" ^ ".join(xor_terms)))
    return "\n".join(lines)


def gen_baseline():
    """points.md #889: the measurement harness with ZERO cell instances -- its own fixed LUT/ALU/DFF/Fmax
    cost, to be subtracted from every other result so the reported per-cell figures are the cell alone,
    not cell-plus-harness. array_alive here depends only on BTN_ENTRY (still real, non-prunable)."""
    lines = [HEADER.format(top="mesh_baseline_0", n=0, module="(none)", rows=0, cols=0, cfg_w_hi=63, cfg_expr=cfg_expr_for(64))]
    lines.append(FOOTER.format(xor_expr="entry_active ^ entry_arrived ^ entry_data[0]"))
    return "\n".join(lines)


def main():
    if sys.argv[1] == "baseline":
        sys.stdout.write(gen_baseline())
        return
    cell_type, n = sys.argv[1], int(sys.argv[2])
    rows = int(sys.argv[3]) if len(sys.argv) > 3 else (3 if n == 9 else 1)
    cols = int(sys.argv[4]) if len(sys.argv) > 4 else (3 if n == 9 else 1)
    if cell_type == "nano":
        sys.stdout.write(gen_nano(n, rows, cols))
    elif cell_type == "command":
        sys.stdout.write(gen_command(n))
    elif cell_type in STANDARD:
        sys.stdout.write(gen_standard(cell_type, n, rows, cols))
    else:
        raise SystemExit(f"no generator for {cell_type!r} (have: {sorted(STANDARD)} + nano + command)")


if __name__ == "__main__":
    main()
