#!/usr/bin/env python3
# STATUS (docs/STATUS_MAP.md, 9 Oct 2026): MEASUREMENT script; results are in the ledger. Re-runnable, not tested. Moved here from tools/.
"""tools/measure_flag_across_families_v1.py -- does `synth_gowin -nowidelut` matter for EVERY family, or only flex? (ledger #950; Alan: "you would have to test
and see if it makes a difference on the nano and sub designs too").

Run: python3 tools/measure_flag_across_families_v1.py [--quick]     (needs yosys; writes only under /tmp; sequential, so minutes on one core)
Three families, one cell of each type, default synth_gowin vs -nowidelut, SYNTHESIS ONLY (no P&R: see measure_synth_flow_v1.py for that):
  * sub  (v4s)  and flex (v4sa): generated by the step-1 assembler itself, synthesised with the generated .ys (so the flag path is exercised end to end)
  * nano (the ORIGINAL v4 cells in fpga/verilog, the family tools/gowin_sizing/size_cells.sh measures): full cells as built (shifter included)
Columns: LUT4 / MUX2_LUT (all) / ALU / DFF.  `--quick` skips the original-family `lean` mode and the slowest multiplier cells.
"""
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # tools/experimental/ -> repo root
sys.path.insert(0, os.path.join(ROOT, "tools"))
import flexsub_assemble_v1 as fsa  # noqa: E402

QUICK = "--quick" in sys.argv
V = os.path.join(ROOT, "fpga", "verilog")


def parse(out):
    c = {m.group(1): int(m.group(2)) for m in re.finditer(r"^\s+(\w+)\s+(\d+)\s*$", out.split("Number of cells")[-1], re.M)}
    return (sum(v for k, v in c.items() if re.fullmatch(r"LUT[1-4]", k)), sum(v for k, v in c.items() if k.startswith("MUX2_LUT")), c.get("ALU", 0),
            sum(v for k, v in c.items() if k.startswith("DFF")))


def row(label, a, b):
    lut = f"{a[0] / b[0]:.2f}x" if b[0] else "n/a"
    mark = "  <== differs" if (a[0] > 1.05 * b[0] + 2) else ""
    print(f"  {label:34s} default {a[0]:>6}/{a[1]:>6}/{a[2]:>4}/{a[3]:>5}   nowidelut {b[0]:>6}/{b[1]:>3}/{b[2]:>4}/{b[3]:>5}   LUT4 default/nowidelut {lut}{mark}", flush=True)
    return a, b


def gen_family(fam):
    tmp = tempfile.mkdtemp(prefix=f"flag_{fam}_")
    res = {}
    for cell in fsa.cells_for(fam):
        if QUICK and cell in ("mul", "mul_dsp", "mul_dsp2", "mul_dsp3"):
            continue
        r = []
        for flag in (False, True):
            d = os.path.join(tmp, f"{cell}_{int(flag)}")
            try:
                rec = fsa.assemble_flexsub(fam, cell, 1, d, width_arg=32 if fam == "flex" else None, nowidelut=flag)   # flex needs a WIDTH: 32, to match the sub cells
            except Exception as e:                                      # a cell that does not generate in this family is reported, not hidden
                r = None
                print(f"  {cell:34s} (not generated: {str(e)[:70]})", flush=True)
                break
            assert ("-nowidelut" in open(os.path.join(d, rec["top"] + ".ys")).read()) == flag, "the flag did not reach the .ys"
            out = subprocess.run(["yosys", "-s", f"{rec['top']}.ys"], cwd=d, capture_output=True, text=True).stdout
            r.append(parse(out))
        if r:
            res[f"{fam}/{cell}"] = row(f"{fam}: {cell}", *r)
    return res


def original_family(mode):
    ADD = "invert_addon_v1.v nibble_mask_addon_v1.v shift_fine_addon_v1.v shift_lane_addon_v1.v shift_lane_addon_v2.v"
    if mode == "lean":
        ADD = os.path.join(ROOT, "tools", "gowin_sizing", "addon_passthrough_stubs.v")
    cells = [("ram_cell_v4", "ram_cell_v4.v"), ("latch_cell_v4", "latch_cell_v4.v"), ("accumulator_cell_v4", "accumulator_cell_v4.v"), ("compare_cell_v4", "compare_cell_v4.v"),
             ("branch_cell_v4", "branch_cell_v4.v"), ("sequencer_cell_v4", "sequencer_cell_v4.v"), ("adder_cell_v4", "adder_cell_v4.v adder_v1.v"), ("nano_gate_v4", "nano_gate_v4.v"),
             ("mul_cell_v4", "mul_cell_v4.v bitwise_multiplier_32bit.v")]
    res = {}
    for top, files in cells:
        if QUICK and top == "mul_cell_v4":
            continue
        r = []
        for flags in ("-noiopads", "-noiopads -nowidelut"):
            out = subprocess.run(["yosys", "-p", f"read_verilog -sv {files} {ADD}; hierarchy -top {top}; synth_gowin -top {top} {flags}; stat"], cwd=V, capture_output=True, text=True).stdout
            r.append(parse(out))
        res[f"nano/{top}/{mode}"] = row(f"nano(v4) {mode}: {top}", *r)
    return res


def main():
    allres = {}
    print("columns:  LUT4 / MUX2_LUT / ALU / DFF   (synthesis only)\n")
    print("SUB family (v4s), one cell each:", flush=True); allres.update(gen_family("sub"))
    print("\nFLEX family (v4sa), one cell each:", flush=True); allres.update(gen_family("flex"))
    print("\nORIGINAL nano family (v4 cells, shifter included), -noiopads as the repo's own sizing script:", flush=True); allres.update(original_family("full"))
    if not QUICK:
        print("\nORIGINAL nano family, `lean` (shifter replaced by pass-through stubs):", flush=True); allres.update(original_family("lean"))
    big = {k: v for k, v in allres.items() if v[0][0] > 1.05 * v[1][0] + 2}
    print(f"\nSUMMARY: {len(allres)} cells measured; the flag changed LUT4 by more than 5% in {len(big)}: {sorted(big)}")
    print(f"         total LUT4 across all measured cells: default {sum(v[0][0] for v in allres.values())}, nowidelut {sum(v[1][0] for v in allres.values())}")


if __name__ == "__main__":
    sys.exit(main())
