`timescale 1ns/1ps
// tb_icm_wired3.v — AUTO-GENERATED by icm_stream.py.
// Replays the 'wired3' ICM stream against the real unicell RTL through the
// target-latch transport (top mux: opcodes 2/3/23 read the held load_target),
// then checks each cell's loaded topology and streamed in/out address.
// iverilog -o tb.vvp tb_icm_*.v unicell_zone.v unicell_array.v unicell.v
module tb_icm_wired3;
    reg clk=0,rst=0; always #5 clk=~clk;
    reg [31:0] cpu_bus=0, cpu_data=0; reg cpu_valid=0;
    localparam [7:0] OP_SET_TARGET=8'd24, OP_LOAD_AT=8'd23;
    reg [15:0] load_target=16'h0;
    always @(posedge clk) if (cpu_valid && cpu_bus[7:0]==OP_SET_TARGET) load_target<=cpu_data[15:0];
    // NEW top mux: opcodes 23 (LOAD_AT), 2 (SET_INPUT), 3 (SET_OUTPUT) read the held target
    wire [15:0] cpu_addr_w = (cpu_bus[7:0]==8'd1) ? cpu_data[31:16]
                          : (cpu_bus[7:0]==OP_LOAD_AT || cpu_bus[7:0]==8'd2 || cpu_bus[7:0]==8'd3) ? load_target
                          : cpu_data[15:0];
    wire preload_act=(cpu_bus[18:17]!=2'b00);
    wire cmd_valid_w=cpu_valid && (cpu_bus[7:0]!=8'd1) && ((cpu_bus[7:0]!=8'd0)||preload_act);
    wire [1:0] tv=0; wire [31:0] ta=0,td=0;
    unicell_zone #(.NUM_CELLS(28),.NUM_BRIDGES(2),.ZONE_ID(0)) z(.clk(clk),.rst(rst),
      .cmd_bus(cpu_bus),.cmd_data(cpu_data),.cmd_valid(cmd_valid_w),.cpu_addr(cpu_addr_w),.cpu_data(cpu_data),.cpu_valid(cpu_valid),
      .out_addr(),.out_data(),.out_valid(),.armed_count(),.arrived_count(),.output_set_count(),.emit_count(),
      .dbg0_cmd_latch(),.dbg0_input_addr(),.dbg0_output_addr(),.dbg0_a_data(),.cycle_count(),
      .bridge_n_in_valid(tv),.bridge_n_in_addr(ta),.bridge_n_in_data(td),.bridge_n_out_valid(),.bridge_n_out_addr(),.bridge_n_out_data(),
      .bridge_s_in_valid(tv),.bridge_s_in_addr(ta),.bridge_s_in_data(td),.bridge_s_out_valid(),.bridge_s_out_addr(),.bridge_s_out_data(),
      .bridge_e_in_valid(tv),.bridge_e_in_addr(ta),.bridge_e_in_data(td),.bridge_e_out_valid(),.bridge_e_out_addr(),.bridge_e_out_data(),
      .bridge_w_in_valid(tv),.bridge_w_in_addr(ta),.bridge_w_in_data(td),.bridge_w_out_valid(),.bridge_w_out_addr(),.bridge_w_out_data());
    task pulse; input [31:0] b,d; begin
        @(negedge clk); cpu_bus<=b; cpu_data<=d; cpu_valid<=1;
        @(posedge clk); #1; cpu_valid<=0; cpu_bus<=0; cpu_data<=0;
        repeat(3) @(posedge clk); #1; end endtask
    integer fails=0;
    task chk; input [15:0] cid; input [9:0] wt; input [15:0] wi, wo;
              reg [9:0] gt; reg [15:0] gi, go; begin
        case (cid)
          0: begin gt=z.cells.cell_array[0].cell_inst.cmd_latch[9:0]; gi=z.cells.cell_array[0].cell_inst.input_address; go=z.cells.cell_array[0].cell_inst.output_address; end
          1: begin gt=z.cells.cell_array[1].cell_inst.cmd_latch[9:0]; gi=z.cells.cell_array[1].cell_inst.input_address; go=z.cells.cell_array[1].cell_inst.output_address; end
          2: begin gt=z.cells.cell_array[2].cell_inst.cmd_latch[9:0]; gi=z.cells.cell_array[2].cell_inst.input_address; go=z.cells.cell_array[2].cell_inst.output_address; end
          default: begin gt=10'h3FF; gi=16'hFFFF; go=16'hFFFF; end
        endcase
        $display("  cell %0d topo=0x%03x(want 0x%03x) in=0x%04x(want 0x%04x) out=0x%04x(want 0x%04x) %s",
                 cid, gt, wt, gi, wi, go, wo, ((gt===wt)&&(gi===wi)&&(go===wo))?"PASS":"** FAIL **");
        if (!((gt===wt)&&(gi===wi)&&(go===wo))) fails=fails+1;
        end endtask
    initial begin
        rst=1; repeat(5)@(posedge clk);#1; rst=0; repeat(2)@(posedge clk);#1;
        $display("=== ICM STREAM replay: wired3 ===");
        pulse(32'h00200008, 32'h00000000);  // ARRAY_RESET (all cells -> boot/physical_mode)
        pulse(32'h00000018, 32'h00000000);  // SET_TARGET cell 0
        pulse(32'h00000002, 32'h00000040);  // SET_INPUT   cell 0 in=0x0040
        pulse(32'h00000003, 32'h00000050);  // SET_OUTPUT  cell 0 out=0x0050
        pulse(32'h00000017, 32'h000008BC);  // LOAD_AT     cell 0 <- gs=0x0BC 0x0BC XOR  in=0x40 out=0x50 (cfg=0x000008BC)
        pulse(32'h00000018, 32'h00000001);  // SET_TARGET cell 1
        pulse(32'h00000002, 32'h00000041);  // SET_INPUT   cell 1 in=0x0041
        pulse(32'h00000003, 32'h00000050);  // SET_OUTPUT  cell 1 out=0x0050
        pulse(32'h00000017, 32'h00000807);  // LOAD_AT     cell 1 <- gs=0x007 0x007 AND  in=0x41 out=0x50 (fan-in to 0x50) (cfg=0x00000807)
        pulse(32'h00000018, 32'h00000002);  // SET_TARGET cell 2
        pulse(32'h00000002, 32'h00000042);  // SET_INPUT   cell 2 in=0x0042
        pulse(32'h00000003, 32'h00000051);  // SET_OUTPUT  cell 2 out=0x0051
        pulse(32'h00000017, 32'h00000824);  // LOAD_AT     cell 2 <- gs=0x024 0x024 OR   in=0x42 out=0x51 (cfg=0x00000824)
        chk(16'd0, 10'h0BC, 16'h0040, 16'h0050);
        chk(16'd1, 10'h007, 16'h0041, 16'h0050);
        chk(16'd2, 10'h024, 16'h0042, 16'h0051);
        if (fails==0) $display("  >>> PASS: all 3 programmed cells match (topology + in/out)");
        else $display("  >>> FAIL: %0d mismatch(es)", fails);
        $finish; end
endmodule
