`timescale 1ns/1ps
// tb_icm_xor_and_or.v — AUTO-GENERATED by icm_stream.py.
// Replays the 'xor_and_or' ICM stream (SET_TARGET,CMD_LOAD_AT pairs) against the
// real unicell RTL through the target-latch transport, then checks each cell's
// loaded topology. Compile: iverilog -o tb.vvp tb_icm_*.v unicell_zone.v unicell_array.v unicell.v
module tb_icm_xor_and_or;
    reg clk=0,rst=0; always #5 clk=~clk;
    reg [31:0] cpu_bus=0, cpu_data=0; reg cpu_valid=0;
    localparam [7:0] OP_SET_TARGET=8'd24, OP_LOAD_AT=8'd23;
    reg [15:0] load_target=16'h0;
    always @(posedge clk) if (cpu_valid && cpu_bus[7:0]==OP_SET_TARGET) load_target<=cpu_data[15:0];
    wire [15:0] cpu_addr_w = (cpu_bus[7:0]==8'd1)?cpu_data[31:16]:(cpu_bus[7:0]==OP_LOAD_AT)?load_target:cpu_data[15:0];
    wire preload_act=(cpu_bus[18:17]!=2'b00);
    wire cmd_valid_w=cpu_valid && (cpu_bus[7:0]!=8'd1) && ((cpu_bus[7:0]!=8'd0)||preload_act);
    wire [1:0] tv=0; wire [31:0] ta=0,td=0;
    unicell_zone #(.NUM_CELLS(28),.NUM_BRIDGES(2),.ZONE_ID(0)) z(.clk(clk),.rst(rst),
      .cmd_bus(cpu_bus),.cmd_data(cpu_data),.cmd_valid(cmd_valid_w),.cpu_addr(cpu_addr_w),.cpu_data(cpu_data),.cpu_valid(cpu_valid),
      .out_addr(),.out_data(),.out_valid(),.armed_count(),.arrived_count(),.output_set_count(),.emit_count(),
      .dbg0_cmd_latch(),.dbg0_input_addr(),.dbg0_output_addr(),.dbg0_a_data(),.cycle_count(),
      .bridge_n_in_valid(tv),.bridge_n_in_addr(ta),.bridge_n_in_data(td),.bridge_n_out_valid(),.bridge_n_out_addr(),.bridge_n_out_data(),
      .bridge_s_in_valid(tv),.bridge_s_in_addr(ta),.bridge_s_in_data(td),.bridge_s_out_valid(),.bridge_s_out_addr(),.bridge_s_out_data(),
      .bridge_e_in_valid(tv),.bridge_e_in_addr(ta),.bridge_e_in_data(td),.bridge_e_out_valid(),.bridge_e_out_addr(),.bridge_e_out_data(),
      .bridge_w_in_valid(tv),.bridge_w_in_addr(ta),.bridge_w_in_data(td),.bridge_w_out_valid(),.bridge_w_out_addr(),.bridge_w_out_data());
    task pulse; input [31:0] b,d; begin
        @(negedge clk); cpu_bus<=b; cpu_data<=d; cpu_valid<=1;
        @(posedge clk); #1; cpu_valid<=0; cpu_bus<=0; cpu_data<=0;
        repeat(3) @(posedge clk); #1; end endtask
    integer fails=0;
    task chk; input [15:0] cid; input [9:0] want; reg [9:0] got; begin
        case (cid)
          0: got = z.cells.cell_array[0].cell_inst.cmd_latch[9:0];
          1: got = z.cells.cell_array[1].cell_inst.cmd_latch[9:0];
          2: got = z.cells.cell_array[2].cell_inst.cmd_latch[9:0];
          default: got = 10'h3FF;
        endcase
        $display("  cell %0d topo=0x%03x want=0x%03x %s", cid, got, want, (got===want)?"PASS":"** FAIL **");
        if (got!==want) fails=fails+1; end endtask
    initial begin
        rst=1; repeat(5)@(posedge clk);#1; rst=0; repeat(2)@(posedge clk);#1;
        $display("=== ICM STREAM replay: xor_and_or ===");
        pulse(32'h00200008, 32'h00000000);  // ARRAY_RESET (all cells -> boot/physical_mode)
        pulse(32'h00000018, 32'h00000000);  // SET_TARGET cell 0
        pulse(32'h00000017, 32'h000008BC);  // LOAD_AT  cell 0 <- gs=0x0BC 0x0BC GS_XOR (cfg=0x000008BC)
        pulse(32'h00000018, 32'h00000001);  // SET_TARGET cell 1
        pulse(32'h00000017, 32'h00000807);  // LOAD_AT  cell 1 <- gs=0x007 0x007 GS_AND (cfg=0x00000807)
        pulse(32'h00000018, 32'h00000002);  // SET_TARGET cell 2
        pulse(32'h00000017, 32'h00000824);  // LOAD_AT  cell 2 <- gs=0x024 0x024 GS_OR (cfg=0x00000824)
        chk(16'd0, 10'h0BC);
        chk(16'd1, 10'h007);
        chk(16'd2, 10'h024);
        if (fails==0) $display("  >>> PASS: all 3 programmed cells match");
        else $display("  >>> FAIL: %0d mismatch(es)", fails);
        $finish; end
endmodule
