// top_xdma_unicell.v — XDMA + AXI-Lite Bridge + UniCell Array
//
// This is the top-level module for the YPCB-00338-1P1 Kintex-7 build.
// It instantiates:
//   1. XDMA IP (Xilinx DMA/Bridge for PCIe, x8 Gen1)
//      - PCIe endpoint, GTX transceivers, BAR0 AXI-Lite user interface
//   2. axi_unicell_bridge — translates AXI-Lite to UniCell bus
//   3. unicell_array      — the UniCell compute array
//
// Host interface:
//   - Linux: xdma.ko driver from Xilinx/dma_ip_drivers
//   - Device: /dev/xdma0_user (BAR0 MMIO)
//   - Python: unicell_tool.py (mmap BAR0, poke registers)
//
// PCIe: x8 Gen1, GTX X0Y16-X0Y23, refclk J8, perst Y26
// Clock: 50 MHz SYS_CLK (AA28) → XDMA MMCM → 125 MHz user clock
// LEDs:  P30=heartbeat, M30=PCIe link up, N30=cell fired

`default_nettype none

module top_xdma_unicell #(
    parameter NUM_CELLS = 100
) (
    // System
    input  wire        SYS_CLK,        // 50 MHz (AA28)
    input  wire        SYS_RSTN,       // Active low (R28)

    // PCIe
    input  wire        pcie_perstn,    // PCIe reset (Y26, active low)
    input  wire        pcie_refclk_p,  // 100 MHz refclk (J8)
    input  wire        pcie_refclk_n,
    input  wire  [7:0] pcie_rx_p,
    input  wire  [7:0] pcie_rx_n,
    output wire  [7:0] pcie_tx_p,
    output wire  [7:0] pcie_tx_n,

    // LEDs (active high, LVCMOS18)
    output wire        led0,           // heartbeat
    output wire        led1,           // PCIe link up
    output wire        led2            // cell fired
);

// ── Clocks and reset ───────────────────────────────────────────────────────
wire user_clk;       // 125 MHz from XDMA MMCM
wire user_resetn;    // active low, synchronised to user_clk
wire user_lnk_up;   // PCIe link status

// PCIe refclk buffer — XDMA requires IBUFDS_GTE2 output
wire pcie_refclk_buf;
IBUFDS_GTE2 refclk_ibuf (
    .I    (pcie_refclk_p),
    .IB   (pcie_refclk_n),
    .CEB  (1'b0),
    .O    (pcie_refclk_buf),
    .ODIV2()
);

// ── AXI-Lite interface (XDMA → bridge) ────────────────────────────────────
wire [31:0] m_axil_awaddr;
wire        m_axil_awvalid;
wire        m_axil_awready;
wire [31:0] m_axil_wdata;
wire  [3:0] m_axil_wstrb;
wire        m_axil_wvalid;
wire        m_axil_wready;
wire  [1:0] m_axil_bresp;
wire        m_axil_bvalid;
wire        m_axil_bready;
wire [31:0] m_axil_araddr;
wire        m_axil_arvalid;
wire        m_axil_arready;
wire [31:0] m_axil_rdata;
wire  [1:0] m_axil_rresp;
wire        m_axil_rvalid;
wire        m_axil_rready;

// ── UniCell bus signals ────────────────────────────────────────────────────
wire  [7:0] cpu_cmd;
wire [15:0] cpu_addr;
wire [31:0] cpu_data;
wire        cpu_valid;
wire        array_rst;
wire [15:0] bus_addr_w;
wire [31:0] bus_data_w;
wire        bus_valid_w;
wire [15:0] out_addr;
wire [31:0] out_data;
wire        out_valid;
wire [15:0] armed_count;
wire [31:0] cycle_count;

// cmd_valid: HIGH only for command opcodes, not data writes (opcode 1) or NOP (0)
wire cmd_valid_w = cpu_valid && (cpu_cmd != 8'd0) && (cpu_cmd != 8'd1);

// ── LED heartbeat ──────────────────────────────────────────────────────────
reg [25:0] hb_counter = 26'h0;
always @(posedge user_clk) hb_counter <= hb_counter + 1;

assign led0 = hb_counter[25];    // ~1 Hz heartbeat
assign led1 = user_lnk_up;       // PCIe link up
assign led2 = out_valid;          // cell fired pulse (visible flash)

// ── XDMA IP instantiation ──────────────────────────────────────────────────
// Generated by Vivado IP Integrator from the YPCB example project.
// Parameters: x8 Gen1, BAR0=4KB AXI-Lite, 125 MHz user clock
// Pin assignments match ypcb003381p1.xdc + gtx_loc.xdc
xdma_0 xdma_inst (
    // PCIe GT
    .sys_clk            (pcie_refclk_buf),
    .sys_rst_n          (pcie_perstn),
    .pci_exp_txp        (pcie_tx_p),
    .pci_exp_txn        (pcie_tx_n),
    .pci_exp_rxp        (pcie_rx_p),
    .pci_exp_rxn        (pcie_rx_n),

    // User clock and reset
    .axi_aclk           (user_clk),
    .axi_aresetn        (user_resetn),
    .user_lnk_up        (user_lnk_up),

    // Interrupt — tie off
    .usr_irq_req        (1'b0),
    .usr_irq_ack        (),

    // Config management interface — tie off (not used)
    .cfg_mgmt_addr      (19'h0),
    .cfg_mgmt_write     (1'b0),
    .cfg_mgmt_write_data(32'h0),
    .cfg_mgmt_byte_enable(4'h0),
    .cfg_mgmt_read      (1'b0),
    .cfg_mgmt_read_data (),
    .cfg_mgmt_read_write_done(),

    // AXI master interface — tie off (we use AXI-Lite only)
    .m_axi_awready      (1'b0),
    .m_axi_wready       (1'b0),
    .m_axi_bid          (4'h0),
    .m_axi_bresp        (2'b0),
    .m_axi_bvalid       (1'b0),
    .m_axi_arready      (1'b0),
    .m_axi_rid          (4'h0),
    .m_axi_rdata        (64'h0),
    .m_axi_rresp        (2'b0),
    .m_axi_rlast        (1'b0),
    .m_axi_rvalid       (1'b0),

    // AXI-Lite master (BAR0 user interface)
    .m_axil_awaddr      (m_axil_awaddr),
    .m_axil_awvalid     (m_axil_awvalid),
    .m_axil_awready     (m_axil_awready),
    .m_axil_wdata       (m_axil_wdata),
    .m_axil_wstrb       (m_axil_wstrb),
    .m_axil_wvalid      (m_axil_wvalid),
    .m_axil_wready      (m_axil_wready),
    .m_axil_bresp       (m_axil_bresp),
    .m_axil_bvalid      (m_axil_bvalid),
    .m_axil_bready      (m_axil_bready),
    .m_axil_araddr      (m_axil_araddr),
    .m_axil_arvalid     (m_axil_arvalid),
    .m_axil_arready     (m_axil_arready),
    .m_axil_rdata       (m_axil_rdata),
    .m_axil_rresp       (m_axil_rresp),
    .m_axil_rvalid      (m_axil_rvalid),
    .m_axil_rready      (m_axil_rready)
);

// ── AXI-Lite → UniCell bridge ──────────────────────────────────────────────
axi_unicell_bridge #(
    .NUM_CELLS  (NUM_CELLS),
    .CELL_STRIDE(32)
) bridge (
    .aclk           (user_clk),
    .aresetn        (user_resetn),

    .s_axil_awaddr  (m_axil_awaddr),
    .s_axil_awvalid (m_axil_awvalid),
    .s_axil_awready (m_axil_awready),
    .s_axil_wdata   (m_axil_wdata),
    .s_axil_wstrb   (m_axil_wstrb),
    .s_axil_wvalid  (m_axil_wvalid),
    .s_axil_wready  (m_axil_wready),
    .s_axil_bresp   (m_axil_bresp),
    .s_axil_bvalid  (m_axil_bvalid),
    .s_axil_bready  (m_axil_bready),
    .s_axil_araddr  (m_axil_araddr),
    .s_axil_arvalid (m_axil_arvalid),
    .s_axil_arready (m_axil_arready),
    .s_axil_rdata   (m_axil_rdata),
    .s_axil_rresp   (m_axil_rresp),
    .s_axil_rvalid  (m_axil_rvalid),
    .s_axil_rready  (m_axil_rready),

    .cpu_cmd        (cpu_cmd),
    .cpu_addr       (cpu_addr),
    .cpu_data       (cpu_data),
    .cpu_valid      (cpu_valid),
    .array_rst      (array_rst),
    .bus_addr       (bus_addr_w),
    .bus_data       (bus_data_w),
    .bus_valid      (bus_valid_w),
    .out_addr       (out_addr),
    .out_data       (out_data),
    .out_valid      (out_valid),
    .armed_count    (armed_count),
    .cycle_count    (cycle_count)
);

// ── UniCell array ──────────────────────────────────────────────────────────
unicell_array #(
    .NUM_CELLS  (NUM_CELLS)
) array (
    .clk            (user_clk),
    .rst            (~user_resetn | array_rst),

    // Command bus
    .cmd_bus        (cpu_cmd),
    .cmd_data       (cpu_data),
    .cmd_valid      (cmd_valid_w),

    // CPU data bus injection
    .cpu_addr       (cpu_addr),
    .cpu_data       (cpu_data),
    .cpu_valid      (cpu_valid && (cpu_cmd == 8'd1)), // DATA_WRITE only

    // Array outputs
    .out_addr       (out_addr),
    .out_data       (out_data),
    .out_valid      (out_valid),
    .armed_count    (armed_count),
    .cycle_count    (cycle_count)
);

endmodule

`default_nettype wire
