# xor_and_or.tcl — AUTO-GENERATED by icm_stream.py
# Streams the ICM 'xor_and_or' as (SET_TARGET, CMD_LOAD_AT) pairs through the
# target latch. Requires the build with SET_TARGET(op24) + CMD_LOAD_AT(op23).
# Reads cell-0 cmd_latch via probe view selector 3 (dbg0_cmd_latch[79:48]).
set INST 0
if {$argc >= 1} { set INST [lindex $argv 0] }
set HWM "USB-Blaster"
if {$argc >= 2} { set HWM [lindex $argv 1] }
set ::INST $INST
proc uc_open {m} { set ns [get_hardware_names]; set ::HW [lindex $ns 0]
    foreach h $ns { if {[string match "*$m*" $h]} { set ::HW $h; break } }
    set ::DEV [lindex [get_device_names -hardware_name $::HW] 0]
    puts "Hardware : $::HW"; puts "Device   : $::DEV"
    start_insystem_source_probe -device_name $::DEV -hardware_name $::HW }
proc uc_close {} { end_insystem_source_probe }
proc sf {snap go cmd data} { set hi [expr {(($snap&1)<<1)|($go&1)}]
    write_source_data -instance_index $::INST -value [format "%x%08x%08x" $hi [expr {$cmd&0xFFFFFFFF}] [expr {$data&0xFFFFFFFF}]] -value_in_hex }
proc cmd {cb cd} { sf 0 0 $cb $cd; sf 0 1 $cb $cd; sf 0 0 $cb $cd }
proc rd_latch {} { sf 1 0 0x00000003 0x0; sf 0 0 0x00000003 0x0
    set v [expr {"0x[string trim [read_probe_data -instance_index $::INST -value_in_hex]]"}]
    return [expr {($v>>48)&0xFFFFFFFF}] }

uc_open $HWM
puts "================= ICM STREAM: xor_and_or ================="
cmd 0x00200008 0x00000000   ;# ARRAY_RESET (all cells -> boot/physical_mode)
cmd 0x00000018 0x00000000   ;# SET_TARGET cell 0
cmd 0x00000017 0x000008BC   ;# LOAD_AT  cell 0 <- gs=0x0BC 0x0BC GS_XOR (cfg=0x000008BC)
cmd 0x00000018 0x00000001   ;# SET_TARGET cell 1
cmd 0x00000017 0x00000807   ;# LOAD_AT  cell 1 <- gs=0x007 0x007 GS_AND (cfg=0x00000807)
cmd 0x00000018 0x00000002   ;# SET_TARGET cell 2
cmd 0x00000017 0x00000824   ;# LOAD_AT  cell 2 <- gs=0x024 0x024 GS_OR (cfg=0x00000824)
set l0 [rd_latch]
puts [format "  cell0 latch topo = 0x%03x  (want 0x0BC)  %s" [expr {$l0 & 0x3FF}] [expr {($l0 & 0x3FF)==0x0BC ? "PASS" : "** FAIL **"}]]
puts "  (only cell-0 latch is probe-visible; the rest are oracle/sim-verified)"
uc_close
puts "=== done ==="
