# wired3.tcl — AUTO-GENERATED by icm_stream.py
# Streams the ICM 'wired3' as targeted (SET_TARGET / SET_INPUT / SET_OUTPUT /
# CMD_LOAD_AT) transactions through the target latch. Requires the build with
# SET_TARGET(op24)+CMD_LOAD_AT(op23) and the address-targeting reflash (top routes
# load_target into cpu_addr_w for opcodes 2/3; cell addr_match-gates SET_IN/OUT).
# Reads cell-0 topology + in/out address via probe view selector 3.
set INST 0
if {$argc >= 1} { set INST [lindex $argv 0] }
set HWM "USB-Blaster"
if {$argc >= 2} { set HWM [lindex $argv 1] }
set ::INST $INST
proc uc_open {m} { set ns [get_hardware_names]; set ::HW [lindex $ns 0]
    foreach h $ns { if {[string match "*$m*" $h]} { set ::HW $h; break } }
    set ::DEV [lindex [get_device_names -hardware_name $::HW] 0]
    puts "Hardware : $::HW"; puts "Device   : $::DEV"
    start_insystem_source_probe -device_name $::DEV -hardware_name $::HW }
proc uc_close {} { end_insystem_source_probe }
proc sf {snap go cmd data} { set hi [expr {(($snap&1)<<1)|($go&1)}]
    write_source_data -instance_index $::INST -value [format "%x%08x%08x" $hi [expr {$cmd&0xFFFFFFFF}] [expr {$data&0xFFFFFFFF}]] -value_in_hex }
proc cmd {cb cd} { sf 0 0 $cb $cd; sf 0 1 $cb $cd; sf 0 0 $cb $cd }
# one snapshot at selector 3; returns the raw probe word
proc rd_raw {} { sf 1 0 0x00000003 0x0; sf 0 0 0x00000003 0x0
    return [expr {"0x[string trim [read_probe_data -instance_index $::INST -value_in_hex]]"}] }

uc_open $HWM
puts "================= ICM STREAM: wired3 ================="
cmd 0x00200008 0x00000000   ;# ARRAY_RESET (all cells -> boot/physical_mode)
cmd 0x00000018 0x00000000   ;# SET_TARGET cell 0
cmd 0x00000002 0x00000040   ;# SET_INPUT   cell 0 in=0x0040
cmd 0x00000003 0x00000050   ;# SET_OUTPUT  cell 0 out=0x0050
cmd 0x00000017 0x000008BC   ;# LOAD_AT     cell 0 <- gs=0x0BC 0x0BC XOR  in=0x40 out=0x50 (cfg=0x000008BC)
cmd 0x00000018 0x00000001   ;# SET_TARGET cell 1
cmd 0x00000002 0x00000041   ;# SET_INPUT   cell 1 in=0x0041
cmd 0x00000003 0x00000050   ;# SET_OUTPUT  cell 1 out=0x0050
cmd 0x00000017 0x00000807   ;# LOAD_AT     cell 1 <- gs=0x007 0x007 AND  in=0x41 out=0x50 (fan-in to 0x50) (cfg=0x00000807)
cmd 0x00000018 0x00000002   ;# SET_TARGET cell 2
cmd 0x00000002 0x00000042   ;# SET_INPUT   cell 2 in=0x0042
cmd 0x00000003 0x00000051   ;# SET_OUTPUT  cell 2 out=0x0051
cmd 0x00000017 0x00000824   ;# LOAD_AT     cell 2 <- gs=0x024 0x024 OR   in=0x42 out=0x51 (cfg=0x00000824)
set v [rd_raw]
set topo [expr {($v>>48)&0x3FF}]
set cin  [expr {($v>>80)&0xFFFF}]
set cout [expr {($v>>32)&0xFFFF}]
puts [format "  cell0 topo=0x%03x (want 0x0BC)  %s" $topo [expr {$topo==0x0BC ? "PASS":"** FAIL **"}]]
puts [format "  cell0 in  =0x%04x (want 0x0040)  %s" $cin [expr {$cin==0x0040 ? "PASS":"** FAIL **"}]]
puts [format "  cell0 out =0x%04x (want 0x0050)  %s" $cout [expr {$cout==0x0050 ? "PASS":"** FAIL **"}]]
puts "  (cell-0 is probe-visible; other cells are oracle/sim-verified)"
uc_close
puts "=== done ==="
