# =============================================================================
# Unicell-Q.sdc — Timing constraints for top_arria10
# IEI Mustang-F100 (Arria 10 GX660, 10AX066H2F34E2SG)
#
# Board reference clock IDENTIFIED (21 Jun 2026): a 100.00 MHz differential
# clock on the CLK_2K_1 pair (E23 = p / E24 = n), confirmed by on-card
# frequency measurement. The fabric divides it by 4 to the 25 MHz target.
#
# Without this file Quartus calls `derive_clocks -period 1.0`, invents a 1 GHz
# clock on every node, and times against it — producing fake violations. The
# real ceiling is the clk_div Fmax (~40 MHz), so 25 MHz has comfortable margin.
# =============================================================================

# --- Board reference clock: 100 MHz, single-ended p-leg on E23 ---------------
create_clock -name CLK_100M -period 10.000 [get_ports CLK_100M]

# --- Fabric clock: clk_div = CLK_100M / 4 = 25 MHz ---------------------------
# Generated by a synchronous 2-bit counter in top_arria10.v:
#     reg [1:0] div_cnt; always @(posedge CLK_100M) div_cnt <= div_cnt + 1;
#     wire clk_div = div_cnt[1];
# div_cnt[1] toggles once every 4 input edges, so it is exactly CLK_100M / 4.
#
# NOTE: if Quartus can't resolve the target node, run `report_clocks` and
# `get_registers *div_cnt*` to confirm the instance path, then adjust the
# get_registers pattern below (e.g. {*div_cnt[1]*}).
create_generated_clock -name clk_div -source [get_ports CLK_100M] -divide_by 4 \
    [get_registers {div_cnt[1]}]

derive_clock_uncertainty

# --- Asynchronous UART I/O --------------------------------------------------
# uart_bridge runs in the clk_div (25 MHz) domain and synchronises RX
# internally; the serial lines are async to the system. (These ports may be
# Fitter-placed for now since first bring-up reads back over ISSP/JTAG, not
# UART — the false paths still apply regardless of pin location.)
set_false_path -from [get_ports UART_RX]
set_false_path -to   [get_ports UART_TX]

# --- Status LEDs: not timing-critical ---------------------------------------
set_false_path -to [get_ports {LED0_N LED1_N}]
