"""tests/vm/test_cordic_baseline_v1.py -- ledger #1036 addendum 58: the hand-written 32-bit CORDIC baselines (fpga/baselines/cordic_z_v1) and the UniCell flex CORDIC
(generated by project_assemble_v1 from nano/examples/cordic_z_convergence.icm-hier.json) agree on 316 inputs (edge cases and random), in iverilog; latencies are
recorded; a deliberately wrong constant is caught. Requires iverilog."""
import os
import shutil
import sys
import tempfile

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import cordic_baseline_v1 as cb  # noqa: E402


@pytest.fixture(scope="module", autouse=True)
def need_iverilog():
    assert shutil.which("iverilog") and shutil.which("vvp"), "iverilog is REQUIRED"


def test_function_matches_the_icm_file():
    assert cb.constants_from_icm() == cb.KS
    assert cb.model(50000) == -404          # the value the VM example test expects
    assert cb.model(0) == -2726             # z == 0 takes the ADD side (route_equal): +45000, then 18435 and 4399 are positive so -26565, -14036, -7125; worked by hand


def test_all_versions_agree_and_latencies():
    out, lat, res = cb.check()
    assert "errors=0 items=316" in res, out[-1500:]
    # (min, max) clock cycles from accepting the item to the result, per design: pipe, hs, iter, unicell, pipe_naive
    assert lat == "LAT min 4 4 5 20 4 max 4 4 5 20 4", lat


def test_a_wrong_constant_is_caught():
    d = tempfile.mkdtemp(prefix="cbbite_")
    try:
        for f in os.listdir(cb.BASE):
            shutil.copy(os.path.join(cb.BASE, f), d)
        p = os.path.join(d, "cordic_z_hs_v1.v")
        t = open(p).read()
        assert "32'sd26565" in t
        open(p, "w").write(t.replace("32'sd26565", "32'sd26566"))
        old = cb.BASE
        cb.BASE = d
        try:
            out, lat, res = cb.check()
        finally:
            cb.BASE = old
        assert "errors=0" not in res and "MISMATCH dut 1" in out
    finally:
        shutil.rmtree(d, ignore_errors=True)
