`timescale 1ns / 1ps
// tb_stub_pio_bridge_0_sim_only.v -- SIMULATION-ONLY stand-in for the IP-
// Catalog-generated pio_bridge_0 (Avalon-ST-to-Avalon-MM PIO bridge for the
// PCIe Hard IP). Like tb_stub_pcie_a10_hip_0_sim_only.v, this exists purely
// so tb_top_arria10_pcie_mux.v / _silent.v can elaborate and run in
// iverilog without a real Quartus install. It does nothing functionally
// (every output tied to constant 0) and must NEVER be used in a real
// synthesis run.
//
// Port list is NOT guessed: transcribed verbatim (names + widths) from
// fpga/ip-reference/pio_bridge_0.cmp, the real VHDL component declaration
// generated by Quartus for the live project's pio_bridge_0 configuration.

module pio_bridge_0 (
    input  wire        clr_st,
    input  wire [3:0] HipCfgAddr_i,
    input  wire [31:0] HipCfgCtl_i,
    input  wire [52:0] TLCfgSts_i,
    output wire [6:0] cpl_err_o,
    output wire        cpl_pending_o,
    output wire [4:0] hpg_ctrler_o,
    input  wire [1:0] CurrentSpeed_i,
    input  wire        pld_clk_inuse,
    output wire        pld_core_ready,
    input  wire        reset_status,
    input  wire        serdes_pll_locked,
    input  wire        testin_zero,
    input  wire [4:0] Ltssm_i,
    input  wire [3:0] LaneAct_i,
    input  wire        derr_cor_ext_rcv,
    input  wire        derr_cor_ext_rpl,
    input  wire        derr_rpl,
    input  wire        dlup_exit,
    input  wire        ev128ns,
    input  wire        ev1us,
    input  wire        hotrst_exit,
    input  wire [3:0] int_status,
    input  wire        l2_exit,
    input  wire        dlup,
    input  wire        rx_par_err,
    input  wire [1:0] tx_par_err,
    input  wire        cfg_par_err,
    input  wire [7:0] ko_cpl_spc_header,
    input  wire [11:0] ko_cpl_spc_data,
    output wire        AvRxmWrite_0_o,
    output wire [15:0] AvRxmAddress_0_o,
    output wire [31:0] AvRxmWriteData_0_o,
    output wire [3:0] AvRxmByteEnable_0_o,
    input  wire        AvRxmWaitRequest_0_i,
    output wire        AvRxmRead_0_o,
    input  wire [31:0] AvRxmReadData_0_i,
    input  wire        AvRxmReadDataValid_0_i,
    input  wire        app_int_ack,
    output wire        app_int_sts,
    input  wire        app_msi_ack,
    output wire [4:0] app_msi_num,
    output wire        app_msi_req,
    output wire [2:0] app_msi_tc,
    input  wire        Clk_i,
    output wire        pm_auxpwr,
    output wire [9:0] pm_data,
    output wire        pme_to_cr,
    output wire        pm_event,
    input  wire        pme_to_sr,
    input  wire [7:0] HipRxStBarDec1_i,
    output wire        HipRxStMask_o,
    input  wire [127:0] HipRxStData_i,
    input  wire        HipRxStSop_i,
    input  wire        HipRxStEop_i,
    input  wire        HipRxStErr_i,
    input  wire        HipRxStValid_i,
    input  wire        HipRxStEmpty_i,
    output wire        HipRxStReady_o,
    input  wire [11:0] tx_cred_data_fc,
    input  wire [5:0] tx_cred_fc_hip_cons,
    input  wire [5:0] tx_cred_fc_infinite,
    input  wire [7:0] tx_cred_hdr_fc,
    output wire [1:0] tx_cred_fc_sel,
    output wire [127:0] HipTxStData_o,
    output wire        HipTxStSop_o,
    output wire        HipTxStEop_o,
    output wire        HipTxStError_o,
    output wire        HipTxStValid_o,
    output wire        HipTxStEmpty_o,
    input  wire        HipTxStReady_i
);

assign cpl_err_o = 7'b0;
assign cpl_pending_o = 1'b0;
assign hpg_ctrler_o = 5'b0;
assign pld_core_ready = 1'b0;
assign AvRxmWrite_0_o = 1'b0;
assign AvRxmAddress_0_o = 16'b0;
assign AvRxmWriteData_0_o = 32'b0;
assign AvRxmByteEnable_0_o = 4'b0;
assign AvRxmRead_0_o = 1'b0;
assign app_int_sts = 1'b0;
assign app_msi_num = 5'b0;
assign app_msi_req = 1'b0;
assign app_msi_tc = 3'b0;
assign pm_auxpwr = 1'b0;
assign pm_data = 10'b0;
assign pme_to_cr = 1'b0;
assign pm_event = 1'b0;
assign HipRxStMask_o = 1'b0;
assign HipRxStReady_o = 1'b0;
assign tx_cred_fc_sel = 2'b0;
assign HipTxStData_o = 128'b0;
assign HipTxStSop_o = 1'b0;
assign HipTxStEop_o = 1'b0;
assign HipTxStError_o = 1'b0;
assign HipTxStValid_o = 1'b0;
assign HipTxStEmpty_o = 1'b0;

endmodule
