#!/usr/bin/env python3
"""cordic_baseline_v1.py -- hand-written 32-bit baseline for the UniCell CORDIC z-convergence example (ledger #1036 addendum 58).

  --check    iverilog: the three hand-written versions (fpga/baselines/cordic_z_v1/) and the UniCell flex design generated by project_assemble_v1
             all give the same answer on the same inputs (edge cases + random), and measure each one's latency in clock cycles.
  --measure  yosys synthesis counts for all four (same script as the assembler writes: synth_gowin -nowidelut) and a place-and-route Fmax on the
             Tang Nano 20K part for each, written to docs/measurements/cordic_baseline_v1.json.
The function (read from nano/examples/cordic_z_convergence.icm-hier.json, checked against the file by this tool): four stages, z > 0 -> z - K else z + K,
K = 45000, 26565, 14036, 7125, 32-bit signed.
"""
import json
import os
import random
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.join(ROOT, "fpga", "baselines", "cordic_z_v1")
ICM = os.path.join(ROOT, "nano", "examples", "cordic_z_convergence.icm-hier.json")
MAN = os.path.join(ROOT, "docs", "man", "tang-nano-20k.man.json")
KS = (45000, 26565, 14036, 7125)


def model(z):
    """The function, in Python (independent of every Verilog file here)."""
    for k in KS:
        z = z - k if z > 0 else z + k
        z = ((z + (1 << 31)) & 0xFFFFFFFF) - (1 << 31)
    return z


def constants_from_icm():
    d = json.load(open(ICM))
    ks = []
    for name in ("stage_0", "stage_1", "stage_2", "stage_3"):
        cs = {c["cell_id"]: c["preload_value"] for c in d["patterns"][name]["cells"] if "preload_value" in c}
        pos, neg = cs["const_pos"], cs["const_neg"]
        assert (pos + neg) & 0xFFFFFFFF == 0, (name, pos, neg)
        ks.append(pos)
    return tuple(ks)


def assemble_unicell(out):
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "project_assemble_v1.py"), "-s", "flex", "--icm", ICM, "--man", MAN, "--output", out],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr[-600:]
    return [os.path.join(out, f) for f in sorted(os.listdir(out)) if f.endswith(".v")]


def testbench(vectors, vec_path, exp_path):
    return f"""`timescale 1ns/1ps
module tb;
  reg clk = 0, rst = 1, cfg_valid = 0; always #5 clk = ~clk;
  localparam N = {len(vectors)};
  reg signed [31:0] vecs [0:N-1];
  reg signed [31:0] expv [0:N-1];
  initial begin $readmemh("{vec_path}", vecs); $readmemh("{exp_path}", expv); end
  reg signed [31:0] zin; reg go;
  // DUT 0: pipe (no handshake) ; 1: hs ; 2: iter ; 3: UniCell ; 4: pipe_naive
  wire [4:0] ack; wire [4:0] ov; wire signed [31:0] od0, od1, od2, od3, od4;
  reg [4:0] vin;
  wire pv = vin[0];
  cordic_z_pipe_v1 d0 (.clk(clk), .rst(rst), .in_data(zin), .in_valid(vin[0]), .out_data(od0), .out_valid(ov[0]));
  assign ack[0] = 1'b1;
  cordic_z_pipe_naive_v1 d4 (.clk(clk), .rst(rst), .in_data(zin), .in_valid(vin[4]), .out_data(od4), .out_valid(ov[4]));
  assign ack[4] = 1'b1;
  cordic_z_hs_v1   d1 (.clk(clk), .rst(rst), .in_data(zin), .in_valid(vin[1]), .in_ack(ack[1]), .out_data(od1), .out_valid(ov[1]), .out_ack(1'b1));
  cordic_z_iter_v1 d2 (.clk(clk), .rst(rst), .in_data(zin), .in_valid(vin[2]), .in_ack(ack[2]), .out_data(od2), .out_valid(ov[2]), .out_ack(1'b1));
  icm_cordic_z_convergence_flex d3 (.clk(clk), .rst(rst), .cfg_valid(cfg_valid), .in_z_input_data(zin), .in_z_input_valid(vin[3]), .in_z_input_ack(ack[3]),
                                    .out_z_output_data(od3), .out_z_output_valid(ov[3]), .out_z_output_ack(1'b1));
  integer i, j, errs, t0 [0:4], lat [0:4], got [0:4], cyc;
  reg signed [31:0] od [0:4];
  always @* begin od[0] = od0; od[1] = od1; od[2] = od2; od[3] = od3; od[4] = od4; end
  reg [4:0] acc, done;
  initial begin
    errs = 0; vin = 0; zin = 0;
    repeat (4) @(posedge clk); rst <= 0;
    repeat (2) @(posedge clk); cfg_valid <= 1; @(posedge clk); cfg_valid <= 0;
    repeat (12) @(posedge clk);
    for (i = 0; i < N; i = i + 1) begin
      zin <= vecs[i]; vin <= 5'b11111; acc = 0; done = 0; cyc = 0;
      for (j = 0; j < 5; j = j + 1) begin t0[j] = 0; lat[j] = -1; got[j] = 0; end
      while (done != 5'b11111 && cyc < 400) begin
        @(posedge clk); cyc = cyc + 1;
        for (j = 0; j < 5; j = j + 1) begin
          if (!acc[j] && vin[j] && ack[j]) begin acc[j] = 1; vin[j] <= 0; t0[j] = cyc; end
          if (acc[j] && !done[j] && ov[j] && !(cyc == t0[j] && j != 0 && 0)) begin
            if (od[j] !== expv[i]) begin errs = errs + 1; $display("MISMATCH dut %0d item %0d z=%0d got %0d want %0d", j, i, vecs[i], od[j], expv[i]); end
            lat[j] = cyc - t0[j]; done[j] = 1;
          end
        end
      end
      if (done != 5'b11111) begin errs = errs + 1; $display("TIMEOUT item %0d done=%b", i, done); end
      $display("LAT %0d %0d %0d %0d %0d", lat[0], lat[1], lat[2], lat[3], lat[4]);
      repeat (6) @(posedge clk);
    end
    $display("RESULT errors=%0d items=%0d", errs, N);
    $finish;
  end
endmodule
"""


def vectors():
    r = random.Random(58)
    v = [50000, 0, 1, -1, 45000, -45000, 45001, 7125, -7125, 2**31 - 1, -2**31, 2**31 - 45000, -2**31 + 45000, -404, 123456789, -123456789]
    v += [r.randint(-2**31, 2**31 - 1) for _ in range(150)]
    v += [r.randint(-120000, 120000) for _ in range(150)]
    return v


def check():
    assert constants_from_icm() == KS, "constants in the ICM file differ from this tool"
    assert model(50000) == -404
    d = tempfile.mkdtemp(prefix="cordicbase_")
    try:
        uc = assemble_unicell(os.path.join(d, "uc"))
        tb = os.path.join(d, "tb.v")
        vs = vectors()
        vp, ep = os.path.join(d, "vecs.hex"), os.path.join(d, "exp.hex")
        open(vp, "w").write("\n".join("%08x" % (v & 0xFFFFFFFF) for v in vs) + "\n")
        open(ep, "w").write("\n".join("%08x" % (model(v) & 0xFFFFFFFF) for v in vs) + "\n")
        open(tb, "w").write(testbench(vs, vp, ep))
        files = [os.path.join(BASE, f) for f in ("cordic_z_pipe_v1.v", "cordic_z_hs_v1.v", "cordic_z_iter_v1.v", "cordic_z_pipe_naive_v1.v")] + uc
        r = subprocess.run(["iverilog", "-g2012", "-o", os.path.join(d, "t.vvp"), tb] + files, capture_output=True, text=True)
        assert r.returncode == 0, r.stderr[:2000]
        out = subprocess.run(["vvp", os.path.join(d, "t.vvp")], capture_output=True, text=True, timeout=1200).stdout
        rows = [[int(x) for x in l.split()[1:]] for l in out.splitlines() if l.startswith("LAT")]
        lat = "LAT min %s max %s" % (" ".join(str(min(r[j] for r in rows)) for j in range(5)), " ".join(str(max(r[j] for r in rows)) for j in range(5)))
        res = next((l for l in out.splitlines() if l.startswith("RESULT")), out[-800:])
        return out, lat, res
    finally:
        shutil.rmtree(d, ignore_errors=True)


DEVICE = "GW2AR-LV18QN88C8/I7"
CST = """IO_LOC "clk" 4;
IO_PORT "clk" IO_TYPE=LVCMOS33 PULL_MODE=NONE;
IO_LOC "sin" 73;
IO_PORT "sin" IO_TYPE=LVCMOS33 PULL_MODE=DOWN;
IO_LOC "sout" 15;
IO_PORT "sout" IO_TYPE=LVCMOS33 DRIVE=8;
"""


def wrapper(kind):
    """The same small shell for every design, so each can be placed with 3 pins: a 32-bit shift register feeds the data in from one pin (valid held high),
    and the result is folded to one registered bit so nothing is optimised away. The shell's own cost is measured separately (kind 'shell')."""
    core = {
        "pipe": ".clk(clk), .rst(rst), .in_data(zin), .in_valid(1'b1), .out_data(od), .out_valid(ov)",
        "pipe_naive": ".clk(clk), .rst(rst), .in_data(zin), .in_valid(1'b1), .out_data(od), .out_valid(ov)",
        "hs": ".clk(clk), .rst(rst), .in_data(zin), .in_valid(1'b1), .in_ack(), .out_data(od), .out_valid(ov), .out_ack(1'b1)",
        "iter": ".clk(clk), .rst(rst), .in_data(zin), .in_valid(1'b1), .in_ack(), .out_data(od), .out_valid(ov), .out_ack(1'b1)",
        "unicell": ".clk(clk), .rst(rst), .cfg_valid(cfgv), .in_z_input_data(zin), .in_z_input_valid(1'b1), .in_z_input_ack(), .out_z_output_data(od), .out_z_output_valid(ov), .out_z_output_ack(1'b1)",
    }
    mod = {"pipe": "cordic_z_pipe_v1", "pipe_naive": "cordic_z_pipe_naive_v1", "hs": "cordic_z_hs_v1", "iter": "cordic_z_iter_v1", "unicell": "icm_cordic_z_convergence_flex"}
    inst = "" if kind == "shell" else f"    {mod[kind]} dut ({core[kind]});\n"
    outs = "assign od = zin; assign ov = 1'b1;" if kind == "shell" else ""
    return f"""`default_nettype none
module wrap_top (input wire clk, input wire sin, output reg sout);
    reg [7:0] por = 8'd0; reg [31:0] zin = 32'd0; wire [31:0] od; wire ov;
    always @(posedge clk) begin por <= por + (por != 8'hFF); zin <= {{zin[30:0], sin}}; sout <= ^od ^ ov; end
    wire rst = (por < 8'd8);
    wire cfgv = (por == 8'd10);
    {outs}
{inst}endmodule
"""


def synth_counts(files, top, extra=""):
    d = tempfile.mkdtemp(prefix="cordicsyn_")
    try:
        open(os.path.join(d, "s.ys"), "w").write(f"read_verilog -sv {' '.join(files)}\nhierarchy -top {top}\nsynth_gowin -top {top} -nowidelut {extra}\nstat\n")
        y = subprocess.run(["yosys", "-s", os.path.join(d, "s.ys")], capture_output=True, text=True).stdout
        c = {}
        for line in y.split("Number of cells")[-1].splitlines():
            p = line.split()
            if len(p) == 2 and p[1].isdigit():
                c[p[0]] = int(p[1])
        return {"LUT": sum(v for k, v in c.items() if k.startswith("LUT")), "ALU": c.get("ALU", 0), "DFF": sum(v for k, v in c.items() if k.startswith("DFF")), "cells": c}
    finally:
        shutil.rmtree(d, ignore_errors=True)


def place_and_route(files, kind, seeds=(1, 2, 3), target=400):
    d = tempfile.mkdtemp(prefix="cordicpnr_")
    try:
        open(os.path.join(d, "w.v"), "w").write(wrapper(kind))
        open(os.path.join(d, "w.cst"), "w").write(CST)
        fl = []
        for f in files:
            shutil.copy(f, d)
            fl.append(os.path.basename(f))
        r = subprocess.run(["yowasp-yosys", "-q", "-p", f"read_verilog -sv w.v {' '.join(fl)} ; hierarchy -top wrap_top ; synth_gowin -family gw2a -top wrap_top -json w.json"], cwd=d, capture_output=True, text=True)
        assert r.returncode == 0, r.stderr[-800:]
        res = []
        for sd in seeds:
            r = subprocess.run(["yowasp-nextpnr-himbaechel-gowin", "--device", DEVICE, "--vopt", "family=GW2A-18C", "--vopt", "cst=w.cst", "--seed", str(sd), "--json", "w.json",
                                "--report", "rep.json", "--freq", str(target), "--timing-allow-fail"], cwd=d, capture_output=True, text=True)
            if r.returncode != 0:
                res.append({"seed": sd, "error": (r.stderr or r.stdout)[-300:]})
                continue
            rep = json.load(open(os.path.join(d, "rep.json")))
            fm = [v["achieved"] for v in rep["fmax"].values()]
            u = rep["utilization"]
            res.append({"seed": sd, "fmax_mhz": round(min(fm), 1) if fm else None, "LUT4": u["LUT4"]["used"], "DFF": u["DFF"]["used"]})
        return res
    finally:
        shutil.rmtree(d, ignore_errors=True)


def measure():
    d = tempfile.mkdtemp(prefix="cordicmeas_")
    try:
        uc = assemble_unicell(os.path.join(d, "uc"))
        B = lambda *n: [os.path.join(BASE, x) for x in n]
        designs = {
            "pipe": (B("cordic_z_pipe_v1.v"), "cordic_z_pipe_v1"),
            "pipe_naive": (B("cordic_z_pipe_naive_v1.v"), "cordic_z_pipe_naive_v1"),
            "hs": (B("cordic_z_hs_v1.v"), "cordic_z_hs_v1"),
            "iter": (B("cordic_z_iter_v1.v"), "cordic_z_iter_v1"),
            "unicell": (uc, "icm_cordic_z_convergence_flex"),
        }
        out = {"what": "32-bit CORDIC z-convergence, 4 stages (nano/examples/cordic_z_convergence.icm-hier.json); hand-written baselines vs the UniCell flex design generated by project_assemble_v1; "
                       "counts: system yosys synth_gowin -nowidelut on the bare design; Fmax: yowasp yosys + nextpnr-himbaechel-gowin, GW2AR-LV18QN88C8/I7, inside a small identical wrapper, "
                       "target 400 MHz (an unreachable target, so the router keeps trying; --timing-allow-fail), three seeds. SYNTHESIS AND PLACE-AND-ROUTE ONLY: nothing run on a board.", "designs": {}}
        for name, (files, top) in designs.items():
            out["designs"][name] = {"synth": synth_counts(files, top), "pnr_in_wrapper": place_and_route(files, name)}
        out["wrapper_alone"] = {"pnr": place_and_route([], "shell", seeds=(1,))}
        return out
    finally:
        shutil.rmtree(d, ignore_errors=True)


if __name__ == "__main__":
    if "--check" in sys.argv:
        out, lat, res = check()
        print(lat)
        print(res)
        sys.exit(0 if "errors=0" in res else 1)
    if "--measure" in sys.argv:
        m = measure()
        os.makedirs(os.path.join(ROOT, "docs", "measurements"), exist_ok=True)
        json.dump(m, open(os.path.join(ROOT, "docs", "measurements", "cordic_baseline_v1.json"), "w"), indent=1)
        for k, v in m["designs"].items():
            print(k, {a: v["synth"][a] for a in ("LUT", "ALU", "DFF")}, [(r.get("fmax_mhz"), r.get("LUT4")) for r in v["pnr_in_wrapper"]])
        print("wrapper alone", m["wrapper_alone"]["pnr"])
        sys.exit(0)
    print(__doc__)
