#!/usr/bin/env python3
"""
man_generate_v1.py — points.md #557: a real MAN file generator, both
CLI and importable, covering the fields any real downstream tool
(`project_assemble_v1.py`, `#552`) actually reads. The FIRST real
generator for this format -- the existing MAN file
(`docs/man/mustang-f100-a10.man.json`) was hand-assembled from
`points.md`'s own record, per its own `generated_by` field, not
produced by any tool.

Real, honest scope: this covers the REQUIRED, structural fields
(device identity, ALM/DSP totals, the real confirmed pin assignments)
in the real MAN schema -- not the full exhaustive device-half dataset
(M20K/DSP column coordinates, PCIe/DDR4 status, provenance narrative)
the existing hand-assembled file also carries. Those remain real,
separate, more detailed additions -- this generator produces a
genuinely valid, schema-compatible, LOADABLE MAN file, not a full
replacement for careful, sourced hand-authoring.
"""

import argparse
import json
import datetime


def build_man(card_id, part, family, jtag_idcode, alm_total, dsp_total,
              m20k_bits, clk_pin, led0_pin, led1_pin, jtag_tck_hz=6000000):
    return {
        "man_version": "1.0",
        "card_id": card_id,
        "generated": datetime.date.today().isoformat(),
        "generated_by": "tools/man_generate_v1.py -- real, minimal, schema-compatible generator (points.md #557). Structural/required fields only -- see the tool's own docstring for real scope.",
        "device": {
            "part": part,
            "family": family,
            "package": None,
            "jtag_idcode": jtag_idcode,
            "alm_total": alm_total,
            "register_total": None,
            "m20k": {"total_bits": m20k_bits, "note": "user-supplied total; column-level detail not populated by this generator", "columns": []},
            "dsp": {"total_blocks": dsp_total, "columns": [], "note": "column-level detail not populated by this generator"},
            "source": "tools/man_generate_v1.py, user-supplied values -- not independently cross-checked against Chip Planner or a real .pin file",
        },
        "board": {
            "name": None,
            "clock": {"CLK_100M": {"pin": clk_pin, "freq_hz": 100000000}, "note": "user-supplied"},
            "leds": {"LED0_N": led0_pin, "LED1_N": led1_pin, "status": "user-supplied -- not independently confirmed stable or physically wired to visible LEDs (see points.md #528 for why this distinction matters)"},
            "jtag": {"programmer": None, "tck_hz": jtag_tck_hz, "note": "user-supplied", "device_pins": {}},
            "configuration": {"note": "not populated by this generator", "pins": {}},
            "pcie": {"hardware_capability": None, "current_architecture_integration": False},
            "ddr4": {"capacity_gb": None, "onboard": None, "current_integration": False},
        },
        "capabilities": {
            "bram": dsp_total is not None or m20k_bits is not None,
            "bram_integrated": False,
            "dsp": dsp_total is not None,
            "dsp_integrated": False,
            "pcie_hardware": None,
            "pcie_integrated": False,
            "ddr4_onboard": None,
            "ddr4_integrated": False,
        },
        "provenance": [
            "Generated by tools/man_generate_v1.py -- real, minimal, structural fields only. Not a substitute for careful, sourced hand-authoring of the full exhaustive schema.",
        ],
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--card-id", required=True)
    ap.add_argument("--part", required=True, help="Device part number, e.g. 10AX066H2F34E2SG")
    ap.add_argument("--family", default="Arria 10", help="Quartus FAMILY string -- use the exact value Quartus itself expects, not a descriptive name")
    ap.add_argument("--jtag-idcode", default=None)
    ap.add_argument("--alm-total", required=True, type=int)
    ap.add_argument("--dsp-total", required=True, type=int)
    ap.add_argument("--m20k-bits", type=int, default=None)
    ap.add_argument("--clk-pin", required=True, help="e.g. PIN_E23")
    ap.add_argument("--led0-pin", required=True, help="e.g. PIN_AE7")
    ap.add_argument("--led1-pin", required=True, help="e.g. PIN_AH2")
    ap.add_argument("--jtag-tck-hz", type=int, default=6000000)
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args()

    man = build_man(
        card_id=args.card_id, part=args.part, family=args.family,
        jtag_idcode=args.jtag_idcode, alm_total=args.alm_total,
        dsp_total=args.dsp_total, m20k_bits=args.m20k_bits,
        clk_pin=args.clk_pin, led0_pin=args.led0_pin, led1_pin=args.led1_pin,
        jtag_tck_hz=args.jtag_tck_hz,
    )
    with open(args.output, "w") as f:
        json.dump(man, f, indent=2)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
