#!/usr/bin/env python3
"""tools/sd_unit_top_v1.py -- ledger #1036: wrap ANY flex design (an ICM file) in the SD-card + ESP32-SPI "small unit" and write a Tang Nano 20K top level with its pin file.

    python3 tools/sd_unit_top_v1.py --icm my.icm --output build_dir [--sd-fast-div 2]

Writes into build_dir: design/ (the generated flex Verilog), rtl/ (the unit's blocks copied from fpga/verilog), unit_top.v, unit_top.cst (pins), lanes.json (which entry port is which word lane,
which exit is which output, the register map), FILES.txt (every source file for a Gowin project), README_UNIT.md (how to use). Lane j of the playout is entry port lanes.json["entries"][j]; words on
the card are item-major, lane-minor, little-endian 32-bit. Pins: SD slot in SPI mode (83 / 82 / 84 / 81) and the PROPOSED ESP32 link on the edge connector (74 SCLK, 73 CS, 75 MOSI, 76 MISO,
77 READY) from docs/man/tang-nano-20k.man.json. NOT yet run on a board.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHIELD_PINS = {"DISP_LATCH": 25, "DISP_CLK": 26, "DISP_DATA": 27, "BUZZER": 28}   # HW-262 shield: display (two 74HC595) and buzzer; NOT yet checked against the board header
RTL = ["sd_unit_v1.v", "sd_stream_v1.v", "sd_spi_v1.v", "spi_bridge_v1.v", "playout_v1.v", "capture_v1.v"]
PINS = {  # docs/man/tang-nano-20k.man.json
    "BOARD_CLK": 4, "SD_CLK": 83, "SD_CMD": 82, "SD_DAT0": 84, "SD_DAT3": 81,
    "SPI_CS_N": 73, "SPI_SCLK": 74, "SPI_MOSI": 75, "SPI_MISO": 76, "READY": 77,
    "LED_N[0]": 15, "LED_N[1]": 16, "LED_N[2]": 17, "LED_N[3]": 18, "LED_N[4]": 19, "LED_N[5]": 20,
    "SENS[0]": 72, "SENS[1]": 71,   # direct sensor inputs 1 and 2 (digital, pulled down); right-hand header next to the ESP32 link pins (NOT yet checked against the board)
    "KEY_S1": 88,   # Tang button S1 (active high, 1k pull-down on the board): press = restart the whole unit (same as power-up)
}


# Design IDs (register 10): the four ASCII letters for the designs the web sketch knows, otherwise the CRC32 of the design's top-module name.
KNOWN_IDS = {"icm_cordic_z_convergence_flex": "CORD", "icm_small_relay_chain_flex": "RELY", "icm_parallel_reduction_tree_flex": "TREE"}


def design_id(top):
    import zlib
    k = KNOWN_IDS.get(top)
    return int.from_bytes(k.encode(), "big") if k else zlib.crc32(top.encode()) & 0xFFFFFFFF


RAW_TOPS = {"icm_cordic_z_convergence_flex"}   # designs that take the bare 16-bit amount (an angle), not the packed SensorTrix word


def build(icm, out, fast_div=2, direct_default=0, shield=False):
    os.makedirs(out, exist_ok=True)
    dd = os.path.join(out, "design")
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "project_assemble_v1.py"), "-s", "flex", "--icm", icm, "--output", dd], capture_output=True, text=True)
    if r.returncode:
        raise SystemExit("the flex generator refused this design:\n" + (r.stderr or r.stdout)[-1500:])
    rec = json.load(open(os.path.join(dd, "ASSEMBLY.json")))
    top = rec["top"]
    text = open(os.path.join(dd, top + ".v")).read()
    ins = sorted(set(re.findall(r"in_(\w+)_data", text)))
    outs = sorted(set(re.findall(r"out_(\w+)_data", text)))
    if not ins or not outs:
        raise SystemExit("the design needs at least one entry and one exit port")
    L, O = len(ins), len(outs)
    os.makedirs(os.path.join(out, "rtl"), exist_ok=True)
    for f in RTL + (["hw262_shield_v1.v"] if shield else []):
        shutil.copy(os.path.join(ROOT, "fpga", "verilog", f), os.path.join(out, "rtl", f))
    conn = ", ".join([f".in_{p}_data(lane_data[{j}*32 +: 32]), .in_{p}_valid(lane_valid[{j}]), .in_{p}_ack(lane_ack[{j}])" for j, p in enumerate(ins)] +
                     [f".out_{p}_data(out_data[{k}*32 +: 32]), .out_{p}_valid(out_valid[{k}]), .out_{p}_ack(out_ack[{k}])" for k, p in enumerate(outs)])
    shield_ports = " output wire DISP_LATCH, output wire DISP_CLK, output wire DISP_DATA, output wire BUZZER," if shield else ""
    shield_inst = ("    // HW-262 shield: the design's newest result (its amount, four hex digits) on the 4-digit display, the buzzer sounds at two or more active sensors. All in the FPGA, no ESP32.\n"
                   "    hw262_shield_v1 SH (.clk(clk), .rst(rst), .enable(direct_on), .value(live_amt), .buzz(live_two), .latch(DISP_LATCH), .sclk(DISP_CLK), .sdata(DISP_DATA), .buzzer(BUZZER));\n") if shield else ""
    v = f"""// unit_top.v -- GENERATED by tools/sd_unit_top_v1.py (ledger #1036). The design "{top}" behind the SD-card + SPI small unit, Tang Nano 20K pins. Do not hand-edit.
`default_nettype none
module unit_top #(parameter INIT_DIV = 34, parameter FAST_DIV = {fast_div}, parameter RSTW = 16) (
    input  wire BOARD_CLK, input wire KEY_S1, input wire [1:0] SENS,{shield_ports}
    output wire SD_CLK, output wire SD_CMD, input wire SD_DAT0, output wire SD_DAT3,
    input  wire SPI_SCLK, input wire SPI_CS_N, input wire SPI_MOSI, output wire SPI_MISO, output wire READY,
    output wire [5:0] LED_N
);
    wire clk = BOARD_CLK;
    reg [RSTW-1:0] rcnt = 0;
    wire rst = ~&rcnt;
    reg [1:0] key_q = 2'b00; always @(posedge clk) key_q <= {{key_q[0], KEY_S1}};
    wire key_down = key_q[1];                      // button S1 held: restart the unit exactly as at power-up
    always @(posedge clk) if (key_down) rcnt <= 0; else if (rst) rcnt <= rcnt + 1'b1;
    reg cfg_done = 1'b0, cfg_valid = 1'b0;
    always @(posedge clk) begin cfg_valid <= 1'b0; if (rst) cfg_done <= 1'b0; else if (!cfg_done) begin cfg_valid <= 1'b1; cfg_done <= 1'b1; end end
    wire [{L}*32-1:0] lane_data; wire [{L - 1}:0] lane_valid, lane_ack;
    wire [{O}*32-1:0] out_data;  wire [{O - 1}:0] out_valid, out_ack;
    wire ready_line, direct_on, live_nz, live_two; wire [15:0] live_amt;
{shield_inst}    sd_unit_v1 #(.LANES({L}), .OUTS({O}), .AW(10), .INIT_DIV(INIT_DIV), .FAST_DIV(FAST_DIV), .DESIGN_ID(32'h{design_id(top):08X}), .NSENS(2), .DIRECT_RAW({1 if top in RAW_TOPS else 0}), .DIRECT_DEFAULT({1 if (direct_default or shield) else 0}), .SENS_INVERT({1 if shield else 0})) U (
        .clk(clk), .rst(rst), .sd_clk(SD_CLK), .sd_mosi(SD_CMD), .sd_miso(SD_DAT0), .sd_cs_n(SD_DAT3),
        .spi_sclk(SPI_SCLK), .spi_cs_n(SPI_CS_N), .spi_mosi(SPI_MOSI), .spi_miso(SPI_MISO),
        .lane_data(lane_data), .lane_valid(lane_valid), .lane_ack(lane_ack), .out_data(out_data), .out_valid(out_valid), .out_ack(out_ack), .ready_line(ready_line), .sens_pins(SENS), .direct_on(direct_on), .live_nz(live_nz), .live_two(live_two), .live_amt(live_amt));
    {top} D (.clk(clk), .rst(rst), .cfg_valid(cfg_valid), {conn});
    assign READY = ready_line;
    // LEDs (active low outputs, lit = true): LED0 heartbeat (FPGA loaded and running); LED1 the ESP32 has pulled CS low at least once;
    // LED2 the ESP32 has clocked SCLK at least once; LED3 the SD card is up and error-free; LED4 a 1 has arrived on MOSI while CS was low
    // (proves the MOSI wire); LED5 unused (in direct mode LED4/LED5 show the result, see below). LED1/LED2/LED4 stay lit until the bitstream is reloaded.
    reg [24:0] hb = 25'd0; reg seen_cs = 1'b0, seen_clk = 1'b0, seen_mosi = 1'b0;
    always @(posedge clk) begin hb <= hb + 1'b1; if (key_down) begin seen_cs <= 1'b0; seen_clk <= 1'b0; seen_mosi <= 1'b0; end else begin if (!SPI_CS_N) seen_cs <= 1'b1; if (SPI_SCLK) seen_clk <= 1'b1; if (!SPI_CS_N && SPI_MOSI) seen_mosi <= 1'b1; end end
    // In DIRECT mode (sensor pins feed the design, register 11) LED4 = the design's newest result has at least two sensors' worth, LED5 = at least one sensor's worth.
    assign LED_N = ~{{direct_on & live_nz, direct_on ? live_two : seen_mosi, ready_line, seen_clk, seen_cs, hb[24]}};
endmodule
`default_nettype wire
"""
    open(os.path.join(out, "unit_top.v"), "w").write(v)
    cst = ["// GENERATED by tools/sd_unit_top_v1.py -- pins from docs/man/tang-nano-20k.man.json (QFN88 package pins; NOT checked on the board).",
           "// The SD pins get the FPGA's internal pull-ups because the board file lists none; the ESP32 link pins are a PROPOSAL (edge connector)."]
    allpins = dict(PINS); allpins.update(SHIELD_PINS if shield else {})
    for name, pin in allpins.items():
        cst.append(f'IO_LOC "{name}" {pin};')
        if name in ("BOARD_CLK", "KEY_S1"):
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=NONE;')
        elif name.startswith("SENS"):
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE={"UP" if shield else "DOWN"};')
        elif name.startswith("SD_"):
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=UP;')
        elif name.startswith("SPI_") and name != "SPI_MISO":
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=DOWN;' if name == "SPI_SCLK" else f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=UP;')
        else:
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 DRIVE=8;')
    open(os.path.join(out, "unit_top.cst"), "w").write("\n".join(cst) + "\n")
    info = {"design_top": top, "entries": ins, "exits": outs, "word_layout": "item-major, lane-minor, little-endian 32-bit words on the card (item k, lane j at word k*LANES + j); results in arrival order",
            "lanes": L, "outs": O, "sd_pins": {k: PINS[k] for k in PINS if k.startswith("SD_")}, "spi_pins": {k: PINS[k] for k in PINS if k.startswith("SPI_") or k == "READY"},
            "design_id": "0x%08X" % design_id(top), "registers": {"0": "ID 0x57320001", "1": "STATUS [0]sd_ready [1]sd_error [2]sd_busy [3]play_busy [4]sd_done [5]play_done [6]capture_nonempty [12:8]err_code", "2": "CONTROL [0]sd_load [1]sd_save [2]play_start [3]capture_clear [4]clear_done",
                          "3": "START_BLOCK", "4": "NBLOCKS", "5": "PLAY_COUNT (words = items*lanes)", "6": "CAP_COUNT (ro)", "7": "SCRATCH", "8": "MAX_OUT: pacing for designs that hold ONE item at a time -- at most this many results outstanding (0 = unlimited)", "9": "RPI: results per item (default 1)", "11": "DIRECT (rw bit 0): 1 = the design is fed from the sensor pins SENS[0..1] (Tang pins 72, 71), not from the playout RAM; the unit powers up in this mode if built with --direct", "12": "LIVE_RESULT (ro): newest result in direct mode", "13": "LIVE_COUNT (ro): results received in direct mode", "14": "SENSOR_PINS (ro): the sensor pins as the FPGA sees them", "10": "DESIGN_ID (ro): which design is loaded (0x%08X)" % design_id(top)},
            "spi": "mode 0, MSB first, SCLK slower than clk/16 (27 MHz -> <= 1.6 MHz). 0x01 WR_REG addr d3..d0 | 0x02 RD_REG addr pad then 4 bytes | 0x03 WR_WORDS hi lo words | 0x04 RD_WORDS hi lo pad words"}
    json.dump(info, open(os.path.join(out, "lanes.json"), "w"), indent=1)
    files = [os.path.join("rtl", f) for f in RTL + (["hw262_shield_v1.v"] if shield else [])] + [os.path.join("design", f) for f in rec["files"] if f.endswith(".v")] + ["unit_top.v"]
    open(os.path.join(out, "FILES.txt"), "w").write("\n".join(files) + "\n")
    open(os.path.join(out, "README_UNIT.md"), "w").write(f"""# Small unit for design `{top}` ({L} entry lanes, {O} exits)
Sources: FILES.txt. Pins: unit_top.cst (top module `unit_top`). Lanes and registers: lanes.json.
Typical sequence over SPI (ESP32): read ID (reg 0) -> wait STATUS bit0 (card up) -> set START_BLOCK / NBLOCKS, CONTROL=1 (load) -> wait STATUS bit4 -> set PLAY_COUNT = items*{L}, CONTROL=4 (play) ->
(a design that holds ONE item at a time, e.g. the CORDIC, needs pacing: CONTROL=8 to clear the capture, MAX_OUT=1, RPI=1 first) poll CAP_COUNT (reg 6) until all results are in -> RD_WORDS from capture address 0 (and/or set START_BLOCK, NBLOCKS and CONTROL=2 to save them to the card; CONTROL=0x10 clears the done bits first).
Use blocks well away from block 0 (a FAT32 card keeps its partition table there): e.g. input at block 16.., results at block 17.. or later. Raw blocks overwrite whatever is there.
NOT run on a board. The SD slot's pull-ups are not listed in the board file: the .cst turns the FPGA's internal pull-ups on for the SD pins.
""")
    return top, ins, outs


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--icm", required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--sd-fast-div", type=int, default=2)
    ap.add_argument("--shield", action="store_true", help="HW-262 shield variant: powers up in direct mode, sensor pins active LOW (the shield buttons), display and buzzer driven from the FPGA")
    ap.add_argument("--direct", action="store_true", help="power up in DIRECT mode: the sensor pins feed the design with no ESP32 involved")
    a = ap.parse_args()
    top, ins, outs = build(a.icm, a.output, a.sd_fast_div, int(a.direct), a.shield)
    print(f"wrote {a.output}: design {top}, {len(ins)} entry lanes {ins}, {len(outs)} exits {outs}")
