#!/usr/bin/env python3
"""tools/sd_unit_top_v1.py -- ledger #1036: wrap ANY flex design (an ICM file) in the SD-card + ESP32-SPI "small unit" and write a Tang Nano 20K top level with its pin file.

    python3 tools/sd_unit_top_v1.py --icm my.icm --output build_dir [--sd-fast-div 2]

Writes into build_dir: design/ (the generated flex Verilog), rtl/ (the unit's blocks copied from fpga/verilog), unit_top.v, unit_top.cst (pins), lanes.json (which entry port is which word lane,
which exit is which output, the register map), FILES.txt (every source file for a Gowin project), README_UNIT.md (how to use). Lane j of the playout is entry port lanes.json["entries"][j]; words on
the card are item-major, lane-minor, little-endian 32-bit. Pins: SD slot in SPI mode (83 / 82 / 84 / 81) and the PROPOSED ESP32 link on the edge connector (74 SCLK, 73 CS, 75 MOSI, 76 MISO,
77 READY) from docs/man/tang-nano-20k.man.json. NOT yet run on a board.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RTL = ["sd_unit_v1.v", "sd_stream_v1.v", "sd_spi_v1.v", "spi_bridge_v1.v", "playout_v1.v", "capture_v1.v"]
PINS = {  # docs/man/tang-nano-20k.man.json
    "BOARD_CLK": 4, "SD_CLK": 83, "SD_CMD": 82, "SD_DAT0": 84, "SD_DAT3": 81,
    "SPI_CS_N": 73, "SPI_SCLK": 74, "SPI_MOSI": 75, "SPI_MISO": 76, "READY": 77,
    "LED_N[0]": 15, "LED_N[1]": 16, "LED_N[2]": 17, "LED_N[3]": 18,
}


def build(icm, out, fast_div=2):
    os.makedirs(out, exist_ok=True)
    dd = os.path.join(out, "design")
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "project_assemble_v1.py"), "-s", "flex", "--icm", icm, "--output", dd], capture_output=True, text=True)
    if r.returncode:
        raise SystemExit("the flex generator refused this design:\n" + (r.stderr or r.stdout)[-1500:])
    rec = json.load(open(os.path.join(dd, "ASSEMBLY.json")))
    top = rec["top"]
    text = open(os.path.join(dd, top + ".v")).read()
    ins = sorted(set(re.findall(r"in_(\w+)_data", text)))
    outs = sorted(set(re.findall(r"out_(\w+)_data", text)))
    if not ins or not outs:
        raise SystemExit("the design needs at least one entry and one exit port")
    L, O = len(ins), len(outs)
    os.makedirs(os.path.join(out, "rtl"), exist_ok=True)
    for f in RTL:
        shutil.copy(os.path.join(ROOT, "fpga", "verilog", f), os.path.join(out, "rtl", f))
    conn = ", ".join([f".in_{p}_data(lane_data[{j}*32 +: 32]), .in_{p}_valid(lane_valid[{j}]), .in_{p}_ack(lane_ack[{j}])" for j, p in enumerate(ins)] +
                     [f".out_{p}_data(out_data[{k}*32 +: 32]), .out_{p}_valid(out_valid[{k}]), .out_{p}_ack(out_ack[{k}])" for k, p in enumerate(outs)])
    v = f"""// unit_top.v -- GENERATED by tools/sd_unit_top_v1.py (ledger #1036). The design "{top}" behind the SD-card + SPI small unit, Tang Nano 20K pins. Do not hand-edit.
`default_nettype none
module unit_top #(parameter INIT_DIV = 34, parameter FAST_DIV = {fast_div}, parameter RSTW = 16) (
    input  wire BOARD_CLK,
    output wire SD_CLK, output wire SD_CMD, input wire SD_DAT0, output wire SD_DAT3,
    input  wire SPI_SCLK, input wire SPI_CS_N, input wire SPI_MOSI, output wire SPI_MISO, output wire READY,
    output wire [3:0] LED_N
);
    wire clk = BOARD_CLK;
    reg [RSTW-1:0] rcnt = 0;
    wire rst = ~&rcnt;
    always @(posedge clk) if (rst) rcnt <= rcnt + 1'b1;
    reg cfg_done = 1'b0, cfg_valid = 1'b0;
    always @(posedge clk) begin cfg_valid <= 1'b0; if (!rst && !cfg_done) begin cfg_valid <= 1'b1; cfg_done <= 1'b1; end end
    wire [{L}*32-1:0] lane_data; wire [{L - 1}:0] lane_valid, lane_ack;
    wire [{O}*32-1:0] out_data;  wire [{O - 1}:0] out_valid, out_ack;
    wire ready_line;
    sd_unit_v1 #(.LANES({L}), .OUTS({O}), .AW(10), .INIT_DIV(INIT_DIV), .FAST_DIV(FAST_DIV)) U (
        .clk(clk), .rst(rst), .sd_clk(SD_CLK), .sd_mosi(SD_CMD), .sd_miso(SD_DAT0), .sd_cs_n(SD_DAT3),
        .spi_sclk(SPI_SCLK), .spi_cs_n(SPI_CS_N), .spi_mosi(SPI_MOSI), .spi_miso(SPI_MISO),
        .lane_data(lane_data), .lane_valid(lane_valid), .lane_ack(lane_ack), .out_data(out_data), .out_valid(out_valid), .out_ack(out_ack), .ready_line(ready_line));
    {top} D (.clk(clk), .rst(rst), .cfg_valid(cfg_valid), {conn});
    assign READY = ready_line;
    assign LED_N = {{3'b111, ~ready_line}};            // LED0 on = the SD card is up
endmodule
`default_nettype wire
"""
    open(os.path.join(out, "unit_top.v"), "w").write(v)
    cst = ["// GENERATED by tools/sd_unit_top_v1.py -- pins from docs/man/tang-nano-20k.man.json (QFN88 package pins; NOT checked on the board).",
           "// The SD pins get the FPGA's internal pull-ups because the board file lists none; the ESP32 link pins are a PROPOSAL (edge connector)."]
    for name, pin in PINS.items():
        cst.append(f'IO_LOC "{name}" {pin};')
        if name == "BOARD_CLK":
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=NONE;')
        elif name.startswith("SD_"):
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=UP;')
        elif name.startswith("SPI_") and name != "SPI_MISO":
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=DOWN;' if name == "SPI_SCLK" else f'IO_PORT "{name}" IO_TYPE=LVCMOS33 PULL_MODE=UP;')
        else:
            cst.append(f'IO_PORT "{name}" IO_TYPE=LVCMOS33 DRIVE=8;')
    open(os.path.join(out, "unit_top.cst"), "w").write("\n".join(cst) + "\n")
    info = {"design_top": top, "entries": ins, "exits": outs, "word_layout": "item-major, lane-minor, little-endian 32-bit words on the card (item k, lane j at word k*LANES + j); results in arrival order",
            "lanes": L, "outs": O, "sd_pins": {k: PINS[k] for k in PINS if k.startswith("SD_")}, "spi_pins": {k: PINS[k] for k in PINS if k.startswith("SPI_") or k == "READY"},
            "registers": {"0": "ID 0x57320001", "1": "STATUS [0]sd_ready [1]sd_error [2]sd_busy [3]play_busy [4]sd_done [5]play_done [6]capture_nonempty [12:8]err_code", "2": "CONTROL [0]sd_load [1]sd_save [2]play_start [3]capture_clear [4]clear_done",
                          "3": "START_BLOCK", "4": "NBLOCKS", "5": "PLAY_COUNT (words = items*lanes)", "6": "CAP_COUNT (ro)", "7": "SCRATCH"},
            "spi": "mode 0, MSB first, SCLK slower than clk/16 (27 MHz -> <= 1.6 MHz). 0x01 WR_REG addr d3..d0 | 0x02 RD_REG addr pad then 4 bytes | 0x03 WR_WORDS hi lo words | 0x04 RD_WORDS hi lo pad words"}
    json.dump(info, open(os.path.join(out, "lanes.json"), "w"), indent=1)
    files = [os.path.join("rtl", f) for f in RTL] + [os.path.join("design", f) for f in rec["files"] if f.endswith(".v")] + ["unit_top.v"]
    open(os.path.join(out, "FILES.txt"), "w").write("\n".join(files) + "\n")
    open(os.path.join(out, "README_UNIT.md"), "w").write(f"""# Small unit for design `{top}` ({L} entry lanes, {O} exits)
Sources: FILES.txt. Pins: unit_top.cst (top module `unit_top`). Lanes and registers: lanes.json.
Typical sequence over SPI (ESP32): read ID (reg 0) -> wait STATUS bit0 (card up) -> set START_BLOCK / NBLOCKS, CONTROL=1 (load) -> wait STATUS bit4 -> set PLAY_COUNT = items*{L}, CONTROL=4 (play) ->
poll CAP_COUNT (reg 6) until all results are in -> RD_WORDS from capture address 0 (and/or set START_BLOCK, NBLOCKS and CONTROL=2 to save them to the card; CONTROL=0x10 clears the done bits first).
Use blocks well away from block 0 (a FAT32 card keeps its partition table there): e.g. input at block 16.., results at block 17.. or later. Raw blocks overwrite whatever is there.
NOT run on a board. The SD slot's pull-ups are not listed in the board file: the .cst turns the FPGA's internal pull-ups on for the SD pins.
""")
    return top, ins, outs


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--icm", required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--sd-fast-div", type=int, default=2)
    a = ap.parse_args()
    top, ins, outs = build(a.icm, a.output, a.sd_fast_div)
    print(f"wrote {a.output}: design {top}, {len(ins)} entry lanes {ins}, {len(outs)} exits {outs}")
