#!/usr/bin/env python3
"""tools/verilog_versions_v1.py -- ledger #1036 addendum 20: write fpga/verilog/VERSIONS.md, an index of every versioned core family under fpga/verilog (v1, v2, v3 ...), which version is the latest, and for each OLDER version what still names it (a Quartus project, a test, a tool, other Verilog). An older version that nothing live names is safe to move to fpga/archive/; one that something names is not. Re-run after changes:  python3 tools/verilog_versions_v1.py"""
import collections
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def rd(p):
    try:
        return open(os.path.join(ROOT, p), errors="ignore").read()
    except OSError:
        return ""


def main():
    files = [f for f in subprocess.check_output(["git", "-C", ROOT, "ls-files"]).decode().split("\n") if f and not f.startswith(("tools/onion/", "archeology/onion"))]
    code = [f for f in files if re.search(r"\.(py|v|vh|sv|tcl|sh|bat|qsf|sdc|json|ys|cst|xdc|txt)$", f)]
    txt = {f: rd(f) for f in code}
    moddef = collections.defaultdict(set)
    for f in code:
        if f.endswith(".v"):
            for m in re.findall(r"^\s*module\s+(\w+)", txt[f], re.M):
                moddef[m].add(f)
    fv = [f for f in files if f.startswith("fpga/verilog/") and f.endswith(".v")]
    fams = collections.defaultdict(list)
    for f in fv:
        stem = os.path.basename(f)[:-2]
        if stem.startswith(("tb_", "top_")):
            continue
        m = re.match(r"^(.*?)_v(\d+)([a-z]*)$", stem)
        if m:
            fams[(os.path.dirname(f), m.group(1))].append((int(m.group(2)), m.group(3), f))
    lines = ["# Verilog versions under fpga/verilog (generated by tools/verilog_versions_v1.py)", "",
             "For each versioned core family: the versions present, and for every OLDER one what still names it. `none` means nothing live does: it can be moved to `fpga/archive/`. Testbenches (`tb_*`) do not count. `v4` / `v4c` and `v1` / `v1c` pairs are variants (the `c` one drops the addon chain for the carrier), not replacements, so they are not listed as older.", "",
             "| Family (folder) | Versions | Older version | Still named by |", "|---|---|---|---|"]
    for (d, fam), v in sorted(fams.items()):
        v.sort()
        if len(v) < 2 or all(not re.match(r"^\d+$", str(a)) for a, _, _ in v):
            continue
        nums = sorted({a for a, _, _ in v})
        if len(nums) < 2:
            continue
        top = nums[-1]
        for a, b, f in v:
            if a == top:
                continue
            stem = os.path.basename(f)[:-2]
            names = {stem} | {m for m in re.findall(r"^\s*module\s+(\w+)", txt.get(f, ""), re.M) if len(moddef[m]) == 1}
            who = []
            for g, t in txt.items():
                if g == f or (os.path.basename(g).startswith("tb_") and g.startswith("fpga/verilog/")):
                    continue
                if os.path.basename(f) in t or any(re.search(r"\b" + re.escape(n) + r"\b", t) for n in names):
                    who.append(g)
            lines.append(f"| `{fam}` ({os.path.relpath(d, 'fpga/verilog') or '.'}) | {', '.join('v%d%s' % (x, y) for x, y, _ in v)} | v{a}{b} | " + ("; ".join("`%s`" % w for w in who[:3]) + (f" (+{len(who)-3} more)" if len(who) > 3 else "") if who else "none") + " |")
    open(os.path.join(ROOT, "fpga", "verilog", "VERSIONS.md"), "w").write("\n".join(lines) + "\n")
    print("wrote fpga/verilog/VERSIONS.md,", len(lines) - 6, "older versions listed")


if __name__ == "__main__":
    main()
